<style type="text/css">
.woman_banner_three { background:url('<?php echo $this->getSkinUrl(); ?>images/zaid/banner_20140211.jpg') no-repeat center top;  background-size: auto 100%; width: 100%; height: 100%; }
.woman_banner_four { background:url('<?php echo $this->getSkinUrl(); ?>images/zaid/banner_campaign_video.jpg') no-repeat center top;  background-size: auto 100%; width: 100%; height: 100%; }
</style>




<div class="section" id="section0">
	<div class="down" id="section1link"><a  href="#"></a></div>
	<div class="banner_container woman_banner_three">&nbsp;</div>
	<?php $model= Mage::getModel("catalog/category") ?>	
	
	<div class="banner_message">
        <div class="banner_message_title">Woman<br>Spring<br>2014</div>
        <!-- <div class="banner_message_text"></div> -->
        <a href="<?php echo $this->getBaseUrl.'woman/category2/woman-dresses.html';?>" class="banner_cta" >shop new in</a>
    </div>
	
</div>
<div class="section" id="section1">
	<div class="up" id="section0link"><a  href="#"></a></div>
	<!-- <div class="down" id="section2link"><a  href="#"></a></div> -->
	<?php  $url= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);  ?>
	<a href="<?php echo $url."fcuk_feb.mp4"?>" class="fancybox iframe">
		<div class="banner_container woman_banner_four">&nbsp;</div>
	</a>	
	<div class="banner_message banner_message_white">
        <div class="banner_message_title">Models<br>In Motion</div>
        <div class="banner_message_text">See what mischief the models got up <br>to on our campaign shoot </div>
        <a href="<?php echo $url."fcuk_feb.mp4"?>" class="fancybox iframe" id="banner_cta_02">watch now</a>        
    </div>
</div>