<style type="text/css">
.banner_one 
{ 
	background:url("<?php echo $this->getSkinUrl(); ?>images/zaid/home_page.jpg") no-repeat center 30px;  
}
.catalog-category-view #section0 { background: #B2B4B3; }
.main-container .main .col-main { padding-bottom: 0; }
</style>
<div class="section" id="section0">
	<!-- <div class="down" id="section1link"><a  href="#"></a></div> -->
	<div class="banner_container banner_one">&nbsp;</div>
	
</div>