<div class="social-container">
	<div class="social-heading"> social +</div>
	<div class="soc_nav">
		<ul>
			<li><a href="https://www.facebook.com/frenchconnectionindia?ref=ts" target="_blank" class="facebook"></a></li>
			<li><a href="https://twitter.com/fcuk_india" target="_blank" class="twitter"></a></li>
			<?php //echo <li><a href="http://www.pinterest.com/fcukindia/" target="_blank" class="google"></a></li> ?>
			<li><a href="http://www.pinterest.com/fcukindia/" target="_blank" class="pinterest"></a></li>
			<li><a href="http://www.youtube.com/user/frenchconnectionIN" target="_blank" class="youtube"></a></li>
			<li><a href="http://www.instagram.com/frenchconnection_in" target="_blank" class="instagram"></a></li>
			<li><a href="http://911fashion.frenchconnection.in" target="_blank" class="blog"></a></li>
		</ul>
	</div>	
<script type="text/javascript">
	jQuery(document).ready(function($){		
		$(".social-heading").click(function(){
			$(".soc_nav").slideToggle();
		});

	});	
</script>
</div>
