<?php
$resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('core_read');
	
		$query = "SELECT * FROM landingpages where catname='home'";
			$result=$read->query($query);
		$landingpage = $result->fetchAll();
		//print_r($landingpage);
		$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		//print_r($mediaurl);
?>

<style>

body {
    background-image: url("<?php echo $mediaurl.''.$landingpage[0]['bannerimage']; ?>");
    background-position: center 24px;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}
 .header-bg-1 {
    background-image: url("<?php echo $this->getSkinUrl(); ?>images/fcukwrapper.jpg");
    background-position: left top;
    background-repeat: repeat-x;
    width: 100%;
	height:128px;
}

.wrapper {
    background: url("<?php echo $this->getSkinUrl(); ?>images/fcukwrapper.jpg") repeat-x scroll 0 0 transparent;
    margin: 0;
    padding: 0;
}

.header-bg{
    background-color: rgba(255, 255, 255, 0.6);
    width: 100%;
}
.home-cat-links {
/*margin-top: 40px;*/
margin-top: 8px;
}
</style>

<div class="main-container home-banner"> 
	<div class="mainArea">
	<script type="text/javascript">jwplayer.key="r/b4lw74MwDzyS+21OqkhxoUGQzsSX3waoxGLg==";</script>
    
		<div id="myElement">Loading the player...</div>
<?php //echo $this->getBaseUrl('media').$landingpage[0]['bannerimage'];?>
	<script type="text/javascript">
		jwplayer("myElement").setup({
			file: "<?php echo $mediaurl.''.$landingpage[1]['video'];?>",
			image: "<?php echo $mediaurl.''.$landingpage[1]['bannerimage'];?>",
			//image: "<?php echo $this->getSkinUrl('images/preview.jpg')?>",
			height: 360,
			width : 640

		});
	</script>
    
	<div class="home-cat-links">
		<a class="women-cat-link" href="<?php echo $this->getUrl('catalog/category/view/id/3');?>"><?php //echo $this->__('WOMAN')?></a>
		<img src="<?php echo $this->getSkinUrl('images/home_banner_link_divide.png');?>" class="cat_link_divider"/>
		<a class="men-cat-link" href="<?php echo $this->getUrl('catalog/category/view/id/4');?>"><?php //echo $this->__('WOMAN')?></a>
		<!--<img src="<?php// echo $this->getSkinUrl('images/home_banner_link_divide.png');?>" class="cat_link_divider"/>
		<a class="homecatlink" href="<?php //echo $this->getUrl('catalog/category/view/id/');?>"><?php //echo $this->__('WOMAN')?></a>		-->
	</div>	
</div>
	<div class="copyright_text">
		Established in 1972, French Connection is a world-renowned fashion brand famed for its high-design approach. In addition to producing seasonal <a href="<?php echo $this->getUrl('catalog/category/view/id/4');?>">menswear</a> and <a href="<?php echo $this->getUrl('catalog/category/view/id/3');?>">womenswear</a> clothing collections, French Connection also offers <a href="/woman/category/accessories.html">accessories</a>.
	</div>
