<?php
$resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('core_read');
	
		$query = "SELECT * FROM man";
			$result=$read->query($query);
		$landingpage = $result->fetchAll();
		print_r($landingpage[0]['image']);
		$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		//print_r($mediaurl);
?>

<style>

body {
  background-image:none !important;;
    background-image: url("<?php echo $mediaurl.''.$landingpage[0]['image']; ?>") !important;
    background-position: center 24px;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}
 .header-bg-1 {
    background-image: url("http://fcuk.iksulabeta.com/skin/frontend/fcuk/default/images/fcukwrapper.jpg");
    background-position: left top;
    background-repeat: repeat-x;
    width: 100%;
	height:128px;
}

.wrapper {
    background: url("http://fcuk.iksulabeta.com/skin/frontend/fcuk/default/images/fcukwrapper.jpg") repeat-x scroll 0 0 transparent;
    margin: 0;
    padding: 0;
}

.header-bg{
    background-color: rgba(255, 255, 255, 0.6);
    width: 100%;
}

</style>


<div class="womenCatTextLinkArea">
<?php $Categoryname=Mage::getSingleton('core/session')->getCategoryname();
Mage::getSingleton('core/session')->unsCategoryname();
 ?>
 <?php if($Categoryname!='home') {?>
<?php echo $landingpage[0]['content'];?>;
 <?php }?>
	 <!--a href="#">shop <span>dresses</span></a>
	 <a href="#">shop <span>tops</span></a>
	 <a href="#">shop <span>coats &amp; jackets</span></a> 
	 <a href="#">shop <span>jeans</span></a>
	 <br/>
	 <a href="#">shop <span>knitwear</span></a> 
	 <a href="#">shop <span>trousers &amp; leggings</span></a> <a href="#">shop <span>accessories</span></a>
	 <a class="shopwNowBtn" href="#">&nbsp;</a-->
 </div>
<div class="womenCatArea">
<div class="womenCatwindow1"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[1]['image']; ?>" alt="" /></a>
	<div class="womenCatwindow5">
		<div class="womenCatwindow3"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[3]['image']; ?>" alt="" /></a></div>
		<div class="womenCatwindow4"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[4]['image']; ?>" alt="" /></a></div>
	</div>
</div>
<div class="womenCatwindow2"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[2]['image']; ?>" alt="" /></a></div>
<div class="copyright_text">Established in 1972, French Connection is a world-renowned fashion brand famed for its high-design approach. In addition to producing seasonal <a href="#">menswear</a> and <a href="#">womenswear</a> clothing collections, French Connection also offers a <a href="#">homeware</a> line, <a href="#">footwear</a> and <a href="#">accessories</a>.</div>
</div>