<?php
$resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('core_read');
	
		$query = "SELECT * FROM landingpages where catname='underwear'";
		$result=$read->query($query);
		$landingpage = $result->fetchAll();
		//print_r($landingpage);
		$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		//print_r($mediaurl);
?>

<style type="text/css">

.category-underwear{background-image:none;}
 .home-banner {
    background-image: url("<?php echo $mediaurl.''.$landingpage[0]['bannerimage']; ?>");
    background-repeat:no-repeat;
    margin: 0;
    padding: 0;
    background-color: #5a9dc7;
	background-repeat: no-repeat;
	background-position: center top;
}
.header-bg-1 {
    background-image: url("<?php echo $this->getSkinUrl('images/fcukwrapper.jpg') ?>");
    background-position: left top;
    background-repeat: repeat-x;
    width: 100%;
	height:128px;
}

 .wrapper {
    background: url("<?php echo $this->getSkinUrl('images/fcukwrapper.jpg') ?>") repeat-x scroll 0 0 transparent;
    margin: 0;
    padding: 0;
}

 .header-bg{
    background-color: rgba(255, 255, 255, 0.6);
    width: 100%;
}

 .home-cat-links {
margin-top: 380px;
*margin-top: 265px;
}
 .copyright_text {
margin-top: 95px;
 background-color: #fff;
 width: 100%;
}
 .home-cat-links{
	list-style: none;
}
 .home-cat-links li span{
	font-size: 20px;
	font-weight: bold;
	color:red;
	padding-left: 10px;
}
 .home-cat-links ul{padding-top: 25px;}
.home-banner img {width: 12%;line-height: 1.4; border: 0;margin-bottom: 17px;}
.home-banner {position: absolute; left:0px; width: 100%; }
.home-banner img:hover{opacity: 0.6;}
 .shopabysale a{margin-left: 130px;}
.home-banner{top:130px; top:130px\9; }
</style>

<div class="main-container home-banner"> 
	<div class="mainArea">
   
		
    
	<div class="home-cat-links" >
		
        <p>
	       <!--<a title="boxers" class="ms-sale_link gateway-man" href="<?php echo $this->getBaseUrl().'underwear/category/underwear-boxers.html'?>">
				<img width="6%;" style="margin-left: 150px;margin-top: 15px" alt="boxers" src="<?php echo $this->getSkinUrl('images/boxers.gif');?>"></a>-->
			<a title="trunks" class="ms-sale_link gateway-man" href="<?php echo $this->getBaseUrl().'underwear/category/underwear-trunks.html'?>">
				<img width="6%;" style="margin-left: 150px;margin-top: 15px" alt="boxers" src="<?php echo $this->getSkinUrl('images/trunk.gif');?>"></a>
			
			<a title="hip-brief" class="ms-sale_link gateway-man" href="<?php echo $this->getBaseUrl().'underwear/category/underwear-hip-brief.html'?>">
				<img width="6%;" style="margin-left: 10px;margin-top: 15px;" alt="hip-brief" src="<?php echo $this->getSkinUrl('images/briefs.gif');?>"></a>

		</p>

		<p><!--<a title="loungewear" class="ms-sale_link gateway-man" href="<?php echo $this->getBaseUrl().'underwear/category/loungewear.html'?>">
				<img width="6%;" style="margin-left: 150px;" alt="loungwear" src="<?php echo $this->getSkinUrl('images/loungwear.gif');?>"></a>-->

			<a title="topwear" class="ms-sale_link gateway-woman" href="<?php echo $this->getBaseUrl().'underwear/category/underwear-topwear.html'?>">
				<img width="6%;" style="margin-left: 210px;" alt="trunks" src="<?php echo $this->getSkinUrl('images/topwear.gif');?>"></a>
		
		</p>
		<!--<p class="shopabysale"><a title="Sale" class="ms-sale_link gateway-man" href="<?php echo $this->getBaseUrl().'underwear/category/underwear-boxers.html'?>">
		<img  style="width:13%;margin-left: 80px;" alt="Sale" src="<?php echo $this->getSkinUrl('images/shop_sale.gif');?>"></a></p>-->
	</div>	
	

		
</div>

	<div class="copyright_text">
		Established in 1972, French Connection is a world-renowned fashion brand famed for its high-design approach. In addition to producing seasonal <a href="/man.html">menswear</a> and <a href="/woman.html">womenswear</a> clothing collections, French Connection also offers <a href="/woman/category/man-accessories.html">accessories</a>.
	</div>
