<?php
$resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('core_read');
	
		$query = "SELECT * FROM landingpages where catname='man'";
			$result=$read->query($query);
		$landingpage = $result->fetchAll();
		//print_r($landingpage);
		$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		//print_r($mediaurl);
?>

<style>

.category-man {
  background-image:none !important;;
    background-image: url("<?php echo $mediaurl.''.$landingpage[0]['bannerimage']; ?>") !important;
    background-position: center 24px;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}
 .header-bg-1 {
    background-image: url("<?php echo $this->getSkinUrl('images/fcukwrapper.jpg');?>");
    background-position: left top;
    background-repeat: repeat-x;
    width: 100%;
	/*height:128px;*/
}

.wrapper {
    background: url("<?php echo $this->getSkinUrl('images/fcukwrapper.jpg');?>") repeat-x scroll 0 0 transparent;
    margin: 0;
    padding: 0;
}

.header-bg{
    background-color: rgba(255, 255, 255, 0.6);
    width: 100%;


}
.womenCatArea {

/*margin-top: 503px;*/
padding: 0 0.2% 0 0.4%;

}

</style>


<div class="womenCatTextLinkArea">
<?php $Categoryname=Mage::getSingleton('core/session')->getCategoryname();
Mage::getSingleton('core/session')->unsCategoryname();
 ?>
	 <a href="<?php echo $this->getBaseUrl().'man/man-accessories.html'?>">shop <span>accessories</span></a>
	 <a href="<?php echo $this->getBaseUrl().'man/man-shirts.html'?>">shop <span>shirts</span></a>
	 <a href="<?php echo $this->getBaseUrl().'man/man-tshirts.html'?>">shop <span>Tshirts</span></a> 
	 <a href="<?php echo $this->getBaseUrl().'man/man-polo-shirts.html'?>">shop <span>polo-shirts</span></a> 
	 <br/>
	
	  <a href="<?php echo $this->getBaseUrl().'man/man-jeans.html'?>">shop <span>jeans</span></a>
	 <a href="<?php echo $this->getBaseUrl().'man/man-bestsellers.html'?>">shop <span>bestsellers</span></a> 
	 <a href="<?php echo $this->getBaseUrl().'man/man-trousers.html/'?>">shop <span>trousers</span></a>
	 <a class="shopwNowBtn" href="<?php echo $this->getBaseUrl().'new-in/man.html'?>">&nbsp;</a>
 </div>
<div class="womenCatArea">
<div class="womenCatwindow1"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[1]['bannerimage']; ?>" alt="" /></a>
	<div class="womenCatwindow5">
		<div class="womenCatwindow3"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[3]['bannerimage']; ?>" alt="" /></a></div>
		<div class="womenCatwindow4"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[4]['bannerimage']; ?>" alt="" /></a></div>
	</div>
</div>
<div class="womenCatwindow2"><a href="#"><img class="transeff" src="<?php echo $mediaurl.''.$landingpage[2]['bannerimage']; ?>" alt="" /></a></div>
<div class="copyright_text">Established in 1972, French Connection is a world-renowned fashion brand famed for its high-design approach. In addition to producing seasonal <a href="<?php echo $this->getBaseUrl().'man.html'?>">menswear</a> and <a href="<?php echo $this->getBaseUrl().'woman.html'?>">womenswear</a> clothing collections, French Connection also offers <a href="<?php echo $this->getBaseUrl().'woman/woman-accessories.html'?>">accessories</a>.</div>
</div>