<div id="newsletter_thankyou_form" class="tcpl_container clearfix">

 <div class="site_form">

   <article class="tcpl_page">

       <header><h1>Thanks for entering our competition.</h1></header>

       <p>We will contact you if you have won. Good luck!</p>

   </article>

 </div>

 <div class="need_help_container">
   <h2>Need Help?</h2>
   <p><a href="<?php echo Mage::getUrl('shipping-delivery/');?>">View Delivery Options</a><br>
   <a href="<?php echo Mage::getUrl('contact-us/');?>">View Returns Options</a></p>
   <p><a href="<?php echo Mage::getUrl('cancellation-refund/');?>">Contact Us</a></p>
 </div>

 <a href="<?php echo Mage::getBaseUrl();?>" class="btnLink btnLink_startshopping"></a>

</div>