<nav class="grid_6 clearfix" id="subNav">
    <div class="clearfix" id="sub_ctrl_toggle">
</div>
<?php
$url=$this->helper('core/url')->getCurrentUrl();
$arr =  explode("/", $url);

?>
 <ul id="accordion">
 	  <li class="subnav_title">ABOUT FRENCH CONNECTION</li>
  <li class="subnav_title_divide"></li>
	<li class="reveal">
		<a href="#">ABOUT</a>
		<ul id="revealchild" <?php if($arr[3]=='the-stores' ||$arr[3]=='fashion-is-our-business' ||$arr[3]=='head-turning-windows' ||$arr[3]=='brand-identity' || $arr[3]=='brand-marketing-communications' || $arr[3]=='brand-advertising'){echo 'style="display:block"';}?>>
			<li><a href="<?php echo $this->getBaseUrl().'fashion-is-our-business'?>"  rel="tab" >Fashion Is Our Business</a></li>
			<li><a href="<?php echo $this->getBaseUrl().'the-stores'?>"  rel="tab" >The Stores</a></li>
			<li><a href="<?php echo $this->getBaseUrl().'head-turning-windows'?>"  rel="tab" >Head Turning Windows</a></li>
			<li><a href="<?php echo $this->getBaseUrl().'brand-identity'?>"  rel="tab">Brand Identity</a></li>
			<li><a href="<?php echo $this->getBaseUrl().'brand-marketing-communications'?>"  rel="tab">Brand Marketing Communications</a></li>
			<li><a href="<?php echo $this->getBaseUrl().'brand-advertising'?>"  rel="tab">Brand Advertising</a></li>
		</ul>
	</li>
	<li class="reveal">
		<a href="#">HISTORY OF ADVERTISING</a>
		<ul id="revealchild" <?php if($arr[3]=='history-of-advertising'){echo 'style="display:block"';}?>>
			<li><a href="<?php echo $this->getBaseUrl().'history-of-advertising'?>">History Of Advertising</a></li>
		</ul>
	</li>
	<li class="reveal">
		<a href="#">CONTACT US</a>
		<ul id="revealchild" <?php if($arr[3]=='contact-us'){echo 'style="display:block"';}?>>
			<li><a href="<?php echo $this->getBaseUrl().'contact-us'?>">Contact Us</a></li>
		</ul>
	</li>
</ul>


     </nav>
	<style>
.cms-page-view .grid_12 h1 {margin: 0 0 20px 0; padding: 0; font-weight: bold; font-size: 2.7em; color: #363536; text-transform: uppercase; line-height: 1; }
.cms-page-view .sidebar .reveal a{font-size:12px;}
.cms-page-view .sidebar .subNav{font-size:12px !important;}
.cms-page-view .sidebar .subnav_title{color: #2F3130;font-size: 1.2em;text-transform: uppercase;font-weight:bold}
.cms-page-view .sidebar .subnav_title1{color: #2F3130;font-size: 1em;text-transform: uppercase;font-weight:bold}
.cms-page-view .subnav_title_divide{border-top: 1px solid #DDDDDD;margin: 5px 0 10px;width: 120px;}
.cms-page-view .sidebar .open ul li{margin:10px 0 10px 10px;}
.cms-page-view .sidebar .open ul li a{text-decoration:none;color:#666666;}
.cms-page-view .sidebar .subNav .open ul li a:hover{text-decoration:none;color:#666666;}
.cms-page-view .sidebar .grid_6{border-right: 1px solid #DDDDDD;margin-right: 29px;min-height: 300px;width: 211px;}
.cms-page-view .sidebar nav#subNav ul ul { display: none; }
.cms-page-view .sidebar .active a {color:#CCC;}
.cms-page-view .sidebar nav#subNav ul li a:link, nav#subNav ul li a:visited {font-weight: bold; text-transform: uppercase; color: #2F3130; padding: 0px 0px 0px 0px; text-decoration: none; font-weight: bold; display: block; }
.cms-page-view .sidebar nav#subNav ul #revealchild li a{font-size:11px;text-decoration: none ;font-weight: normal;text-transform: none !important;color: #666666 !important;padding:0px 0px 4px 5px; }
.cms-page-view .sidebar nav#subNav ul #revealchild{padding:8px 10px;}
.cms-page-view .sidebar #subNav {display: block;}


	</style>

	<script type="text/javascript">
	jQuery(function () {
		
		jQuery('#accordion > li').click(function () {
		//jQuery('#accordion > li a').addClass('current');
	    jQuery(this).addClass('active').siblings('li').removeClass('active');
	    jQuery(this).siblings('li').find('ul').slideUp('fast');
	    jQuery('> ul', this).slideDown('fast');
		});
	});

	</script>
