<article class="grid_18 backpage">
    <header><h1>History of Advertising</h1></header>
        <div class="slides history-of-advertising history-of-advertising-intro">
        <p><img alt="2010" class="history-of-advertising-intro-title" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2010_big_1.gif">
       
        <a class="roll-trans" href="#">
             <img class="img-margin-bottom history-of-advertising-intro-first" alt="A/W The Man &amp; the Woman Prepare For Winter" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2010_man_woman.jpg">
        </a>

        <a class="roll-trans" title="2010" href="#">
             <img border="0" class="img-margin-right img-margin-bottom" alt="2010" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2010_history.jpg">
        </a>

        <a class="roll-trans" title="2009" href="#">
            <img class="img-margin-right img-margin-bottom" alt="2009 History" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2009_history.jpg">
        </a>

        <a class="roll-trans" title="2009" href="#">
            <img class="img-margin-bottom" alt="2009" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2009_history_2.jpg">
        </a><br>
        <a class="roll-trans" title="2008" href="#">
            <img class="img-margin-right img-margin-bottom" alt="2008" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2008_history.jpg">
        </a>

        <a class="roll-trans" title="2008" href="#">
        <img class="img-margin-right img-margin-bottom" alt="2008" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2008_history_2.jpg">
        </a>

        <a class="roll-trans" title="2007" href="#">
        <img class="img-margin-bottom" alt="2007" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2007_history.jpg">
        </a>

        <a class="roll-trans" title="2007" href="#">   
         <img class="img-margin-right" alt="2007" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2007_history_2.jpg">
        </a>

        <a class="roll-trans" title="2006" href="#">
         <img class="img-margin-right" alt="2006" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2006_history.jpg">
        </a>

        <a class="roll-trans" title="2006" href="#">
         <img alt="2006" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2006_history_2.jpg">
        </a></p>

        <a class="roll-trans" title="2005" href="#">
        <img border="0" class="img-margin-right img-margin-bottom" alt="2005" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2005_history.jpg">
        </a>

        <a class="roll-trans" title="2005" href="#">
        <img class="img-margin-right img-margin-bottom" alt="2005" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2005_history_2.jpg">
        </a>

        <a class="roll-trans" title="2005" href="#">
        <img class="img-margin-bottom" alt="2004" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2004_history.jpg">
        </a><br>

        <a class="roll-trans" title="2004" href="#">
        <img class="img-margin-right img-margin-bottom" alt="2004" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2004_history_2.jpg">
        </a>

        <a class="roll-trans" title="2003" href="#">
        <img class="img-margin-right img-margin-bottom" alt="2003" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2003_history.jpg">
        </a>

        <a class="roll-trans" title="2003" href="#">
        <img class="img-margin-bottom" alt="2003" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2003_history_2.jpg">
        </a>

        <a class="roll-trans" title="2002" href="#">
        <img class="img-margin-right" alt="2002" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2002_history.jpg">
        </a>

        <a class="roll-trans" title="2006" href="#">
        <img class="img-margin-right" alt="2006" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2002_history_2.jpg"></a>

        <a class="roll-trans" title="2006" href="#">
        <img alt="2006" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2001_history.jpg">
        </a><p></p>

        <a class="roll-trans" title="2001" href="#">
        <img border="0" class="img-margin-right img-margin-bottom" alt="2001" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2001_history_2.jpg">
        </a>

        <a class="roll-trans" title="2000" href="#">
        <img class="img-margin-right img-margin-bottom" alt="2000" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2000_history.jpg">
        </a>

        <a class="roll-trans" title="2000" href="#">
        <img class="img-margin-bottom" alt="2000" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/2000_history_2.jpg">
        </a><br>

        <a class="roll-trans" title="1999" href="#">
         <img class="img-margin-right img-margin-bottom" alt="1999" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1999_history.jpg">
        </a>

        <a class="roll-trans" title="1999" href="#">
            <img class="img-margin-right img-margin-bottom" alt="1999" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1999_history_2.jpg">
        </a>
        <a class="roll-trans" title="1998" href="#">
            <img class="img-margin-bottom" alt="1998" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1998_history.jpg">
        </a>

        <a class="roll-trans" title="1998" href="#">
           <img class="img-margin-right" alt="1998" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1998_history_2.jpg">
        </a>
        
        <a class="roll-trans" title="1997" href="#">
          <img class="img-margin-right" alt="1997" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1997_history.jpg">
        </a>

        <a class="roll-trans" title="1997" href="#">
           <img alt="1997" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/'; ?>images/marketing/1997_history_2.jpg">
        </a>
        <p></p>
      </div>
    </article>
    <style>
.grid_18 {
    width: 733px;
}
article.backpage {
    padding: 0 0 50px;
}
.grid_18{
    display: inline;
    float: left;
    margin-left: 3px;
    margin-right: 2px;
    position: relative;

    </style>s