<?php
		$collection = Mage::getModel('lookbook/lookbook')->getCollection()
		 			->addFieldToFilter('category', '0');
		$landingpage = $collection->getData();
		$mediaurl=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>

	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>images/images/styles.css" />

	<script src="<?php echo $this->getSkinUrl(); ?>images/images/jquery.bxslider2.min.js" type="text/javascript"></script>
		
	<script type="text/javascript" charset="utf-8">
		SyntaxHighlighter.all();
	</script>
    <script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery("#mydiv<?php echo $landingpage[0]['id'] ?>").fadeIn(1000);
		jQuery(".image<?php echo $landingpage[0]['id'] ?> img").css("opacity","1"); 
	//	jQuery("#mydiv1").addClass('active');
	
	});
	
var browserType;

if (document.layers) {browserType = "nn4"}
if (document.all) {browserType = "ie"}
if (window.navigator.userAgent.toLowerCase().match("gecko")) {
   browserType= "gecko"
}

function showmyDiv(id,total)
{
	for(var i=0;i<total;i++)
	{
		if(i==0)
		{
			
		}
		else if(i==id)
		{
		  jQuery("#mydiv"+i).fadeIn(1000);		  
		  jQuery(".image"+id+" img").css("opacity","1"); 		  
		//  alert(id);
		  
		}
		else
		{
			jQuery("#mydiv"+i).fadeOut(500);
			jQuery(".image"+i+" img").css("opacity","0.7"); 
		}
	}
}
jQuery(function(){
	jQuery('#slides1').bxSlider({
		prev_image: '<?php echo $this->getSkinUrl();?>images/images/btn_arrow_left.png',
		next_image: '<?php echo $this->getSkinUrl();?>images/images/btn_arrow_right.png',
		wrapper_class: 'slides1_wrap',
		margin: 70,
		auto: false,
		auto_controls: true
	});
});
</script>
<script type="text/javascript">
showmyDiv(<?php echo $landingpage[0]['id'] ?>,50);		
</script>

	<!--title>bxSlider | jQuery Content Slider Plugin</title-->
	

<!-- end header_inner, header -->
<div class="lookArea">
<?php //echo Mage::getBaseUrl('media').'/images/images/scripts.js'; ?>
<div class="modelview">
    	<?php foreach($collection->getData() as $thumbnail){ ?>
					<div id="mydiv<?php echo $thumbnail['id']?>" class="modelviewArea">
						<img src="<?php echo $mediaurl.''.$thumbnail['thumbnailimage']; ?>" alt=""/>
						<div class="shopLookArea">
						<?php if($thumbnail['shopbylooksku']==''){?>
						<a href="<?php echo $thumbnail['shopbylookurl']; ?>"><img src="<?php echo $this->getSkinUrl(); ?>images/images/shop_look.png" alt="" class="shopImgSty"/></a>
						<?php }else{?>
							<a href="<?php echo $this->getBaseUrl().'lookbook/index/view?productlist='.$thumbnail['shopbylooksku']; ?>"><img src="<?php echo $this->getSkinUrl(); ?>images/images/shop_look.png" alt="" class="shopImgSty"/></a>
							<?php }?>
							<ul>
								
									<?php 
								//get value of sku
								//explode
								//logic for load product by sku and get name and product url from array
								///$abcd='SSAL9,TSAK9,SBQK9,52AX9';
								
								$tags = explode(",", $thumbnail['productsku']);
								if($tags!=''){
							    // print_r($tags);
								foreach ($tags as $tag) {
								
										 $productid = Mage::getModel('catalog/product')->getIdBySku($tag);

										 if($productid) {

												 	//$_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $tag);
												 	  $_product = Mage::getModel('catalog/product')->load($productid);  
													 //	$_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $tag);
													$productid=$_product->getData('entity_id');
																						
													// 	$_product = Mage::getModel('catalog/product')->load($productid);
												
												 	$productname=$_product->getData('name');
												 	$producturl=$_product->getData('url_path');
												 	$productlink=$this->getBaseurl().''.$producturl;
													
												 	echo "<li><a href=".$productlink.">".$productname."</a></li>";	

												 }
										}
									}
								
								
								?>
								
																
							</ul>
						</div>
					</div>
			<?php }?>
</div>

<div id="content_inner">
  <!-- end intro -->
  <!-- end sidebar_right -->
  <?php $count=1;?>
	  <?php $p=count($collection->getData());?>
	  <?php //$mediaurl.''.$landingpage[0]['smallimage']; ?>
<ul id="slides1">
				<?php $active=1;?>
				<?php foreach($collection->getData() as $lookbookval) {?>
				<?php if($count%12==1){echo '<li>';}?>
					<?php// print_r($lookbookval);?>
				<div class="lookbooksmallthumbArea">
				<?php if($active==1){$aclass='active';}?>
				<a id="<?php echo $lookbookval['id'];?>" href="#"  <?php echo 'class=image'.$lookbookval['id'];?> onClick="showmyDiv(<?php echo $lookbookval['id'];?>,50);">
				<img src="<?php echo $mediaurl.''.$lookbookval['smallimage']; ?>" alt=""/>
				</a>
				</div>
				
           	<?php if($count%12==0 ||$p==0){echo '</li>';} $count=$count+1;$p=$p-1;?>
			
				<?php }?>
			
	</ul>
</div>
</div>
