<script type="text/javascript">// <![CDATA[
// <![CDATA[
/* jQuery('#zipcode').keyup(function() {
    var $th = $(this);
    jQueryth.val( $th.val().replace(/[^a-zA-Z0-9]/g, function(str) { alert('You typed " ' + str + ' ".\n\nPlease use only letters and numbers.'); return ''; } ) );
});	

jQuery("#zipcode").keyup(function(event){
    if(event.keyCode == 13){
        $("#button").click();
    }
}); */
	jQuery(document).ready(function($) {
/*jQuery('#zipcode').keyup(function() {
 var pincode = jQuery('#zipcode').val();
  //alert('Handler for keyup() called.');
  if(!pincode.match(/^\d+/))
        {
							jQuery('.shipping_methods').hide();
							jQuery('.no_shipping_available').hide();
							jQuery('.pincodeerror').css('display','block');
							jQuery('.pincodeerror').html('Oops! Please enter a 6 digit PIN code');
							jQuery('.pincodeerror').delay(3000).fadeOut();
        }
});*/
 $('#zipcode').keypress(function(e) {
        if(e.which == 13) {
           // alert();
            checkpin();
        }
    });
});
function checkpin(){
	jQuery(function($){
		 var pincode = jQuery('#zipcode').val();
		  
		 if(pincode=='')
		 {
	//	 alert('please enter pincode');
		 //jQuery('.pincodeerror_message').html('please enter pin code');
		jQuery('.no_shipping_available').hide();
		jQuery('.pincodeerror').css('display','block');
		jQuery('.pincodeerror').html('Enter a 6 digit PIN code');
		jQuery('.pincodeerror').delay(3000).fadeOut();
				 
		 }
		else
		{
		 	//jQuery('.pincodeerror').css('display','none');
					var pattern = /^\d{6}$/;
						if (!pattern.test(pincode)) 
						{
							jQuery('.shipping_methods').hide();
							jQuery('.no_shipping_available').hide();
							jQuery('.pincodeerror').css('display','block');
							jQuery('.pincodeerror').html('Oops! Please enter a 6 digit PIN code');
							jQuery('.pincodeerror').delay(3000).fadeOut();
							//alert('not a number');
											
						}
						else
						{	
					
						
				
	//	alert(pincode);//return false;
			 $.ajax({
						type: "POST",
						url: "<?php echo $this->getUrl('check/index/check'); ?>",

						data: {pincode:pincode},
						success: function(msg){
						
							//alert(msg);
							
							/*if(msg =='cod')
							{
							//	billing.save();
							
							jQuery('#all').show();
								
							}
							else
							{
							if(msg =='ncod')
							{
									
						//	billing.save();
							
							}
							else{
							if(msg=='ocod')
							{
						//	   billing.save();
							jQuery('#oall').show();
							}
						    else
							  {     if(msg=='none')
								{	 //   $("#nall").fadeIn();
									jQuery('#nall').show();
								   //alert('This pincode is not servicable.');
							    }
								}
								}
						}	*/
						
						switch(msg)
						{
								case 'cod': //alert('i m in cod switch'); //for cod no east zone
											jQuery('#all').show();
											jQuery('#nall').hide();
											jQuery('#oall').hide();
											jQuery('#none').hide();
								break;
								case 'ncod': //alert('i m in ncod switch');//
											jQuery('#nall').show();
											jQuery('#all').hide();
											jQuery('#oall').hide();
											jQuery('#none').hide();
								break;
								case 'ocod': //alert('i m in only cod switch');
											 jQuery('#oall').show();
											jQuery('#all').hide();
											jQuery('#nall').hide();
											jQuery('#none').hide();
								break;
								case 'none': //alert('i m in none switch');
											 jQuery('#none').show();
											 jQuery('#oall').hide();
											jQuery('#all').hide();
											jQuery('#nall').hide();
								break;
								//default: caption ="default";
						}
						
						
						}
					
		});
	
		 }}	

	});
	}
// ]]></script>

<div class='shipping_methods_container'>
  <div class="field">
    <label class="required" for="zipcode">Know if your pin-code is serviceable or not</label>
    <div class="input-box">
      <input id="zipcode" class="zipcode"title="Zip/Postal Code" type="text" name="zipcode" value="" maxlength=6 />
      <button class="button" id="button "title="Check Pin" onclick="checkpin()" type="button"><span><span> Validate </span></span></button>
    </div>
  </div>
  <div id="all" class='shipping_methods' style="display: none;">
    <p>Available Payment Methods:</p>
    <ul>
      <li class="available_method">Cash On Delivery</li>
      <li class="available_method">By Credit Card</li>
      <li class="available_method">By Debit Card</li>
      <li class="available_method">Net Banking</li>
    </ul>
  </div>
  <div id="nall" class='shipping_methods' style="display: none;">
    <p>Available Payment Methods:</p>
    <ul>
      <li class="available_method">By Credit Card</li>
      <li class="available_method">By Debit Card</li>
      <li class="available_method">Net Banking</li>
      <li class="not_available_method">Cash On Delivery</li>
    </ul>
  </div>
  <div id="oall" class='shipping_methods' style="display: none;">
    <p>Available Payment Methods:</p>
    <ul>
      <li class="available_method">Cash On Delivery</li>
      <li class="not_available_method">By Credit Card</li>
      <li class="not_available_method">By Debit Card</li>
      <li class="not_available_method">Net Banking</li>
    </ul>
  </div>
  <div id="none" class='shipping_methods no_shipping_available' style="display: none;">Sorry, No Payment Method is Available in your Region.</div>
  <span class="pincodeerror shipping_methods pincodevalidation" style="color:red;display: none;"></span> </div>
