<div class="size-chart-outer-container">
<div id="size-fit-popup">
<div align="center">
<h2 class="size-chart-title">French Connection Size Guide</h2>
<table class="size-guide">
<tbody>
<tr><th colspan="9">
<h3>MENSWEAR UNDERWEAR SIZE GUIDE</h3>
</th></tr>
<tr><th>&nbsp;</th>
<td>XS</td>
<td>S</td>
<td>M</td>
<td>L</td>
<td>XL</td>
<td>XXL</td>
</tr>
<tr><th>BOXER<br /> INCHES</th>
<td>NA</td>
<td>28-30"</td>
<td>32-34"</td>
<td>36-38"</td>
<td>40-42"</td>
<td>NA</td>
</tr>
<tr><th>CM</th>
<td>NA</td>
<td>71-76cm</td>
<td>81-86cm</td>
<td>91-97cm</td>
<td>102-107cm</td>
<td>NA</td>
</tr>
<tr><th>BRIEF/HIP BRIEF<br /> INCHES</th>
<td>NA</td>
<td>28-30"</td>
<td>32-34"</td>
<td>36-38"</td>
<td>40-42"</td>
<td>NA</td>
</tr>
<tr><th>CM</th>
<td>NA</td>
<td>71-76cm</td>
<td>81-86cm</td>
<td>91-97cm</td>
<td>102-107cm</td>
<td>NA</td>
</tr>
<tr><th>TRUNKS<br /> INCHES</th>
<td>NA</td>
<td>28-30"</td>
<td>32-34"</td>
<td>36-38"</td>
<td>40-42"</td>
<td>NA</td>
</tr>
<tr><th>CM</th>
<td>NA</td>
<td>71-76cm</td>
<td>81-86cm</td>
<td>91-97cm</td>
<td>102-107cm</td>
<td>NA</td>
</tr>
<tr><th>VESTS<br /> INCHES</th>
<td>NA</td>
<td>36"</td>
<td>38-40"</td>
<td>42-44"</td>
<td>46-48"</td>
<td>NA</td>
</tr>
<tr><th>CM</th>
<td>NA</td>
<td>91cm</td>
<td>97-102cm</td>
<td>107-112cm</td>
<td>117-122cm</td>
<td>NA</td>
</tr>
<tr><th>CREW NECKS<br /> INCHES</th>
<td>NA</td>
<td>36"</td>
<td>38-40"</td>
<td>42-44"</td>
<td>46-48"</td>
<td>NA</td>
</tr>
<tr><th>CM</th>
<td>NA</td>
<td>91cm</td>
<td>97-102cm</td>
<td>107-112cm</td>
<td>117-122cm</td>
<td>NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>