<style>

.leftmenu a{
	text-decoration:none;
	color:#4A4A4A;
	font-weight:normal;
	
	}
	.leftmenu a:visited,.leftmenu a:hover{
	text-decoration:none;
	color:#4A4A4A;
	font-weight:bold;
	
	}
.breadcrumbs 
{
display:none;	
}


.main_content_image 
{
	right:0 !important;
}
.leftmenu
{
 float: left;
    font-size: 11px;
    font-weight: bold;
    padding-left: 10px;
    text-align: left;
    width: 155px;

}
.rightstore {
margin-top:30px;
    float: right;
    font-size: 11px;
    margin-right: 20px;
    text-align: left;
    width: 750px;
}
.storetitle {
    background-color: #DCDCDC;
    font-weight: bold;
    height: 12px;
    padding: 10px;
}
.storeheading {
    border-bottom: 1px solid #4A4A4A;
    font-size: 12px;
    font-weight: bold;color: #4A4A4A;
}
.white {
    background-color: #FFFFFF;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.lightgrey {
    color: #4A4A4A;
}
.lightgrey {
    background-color: #F4F4F4;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.storename {
    float: left;
    font-size: 12px;
    font-weight: bold;
    margin-right: 20px;
    width: 150px;color: #4A4A4A;
}
.white .storename,.lightgrey .storename{
    float: left;
    font-size: 12px;
    font-weight: normal;
    margin-right: 20px;
    width: 150px;color: #4A4A4A;
}

.storeAddress {
    float: left;
    font-size: 12px;
    margin-right: 20px;
    width: 330px;color: #4A4A4A;
}
.storeContact {
    float: left;
    font-size: 12px;
    width: 110px;color: #4A4A4A;
}	
</style>


<div class="leftmenu">
      	<p style="padding-top:14px;"></p>	
      	<p class="sl-left-menu-pad"><a href="/stores_agra">Agra</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_ahmedabad">Ahmedabad</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_amritsar">Amritsar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bangalore">Bangalore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bhopal">Bhopal</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bhubaneswar">Bhubaneswar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bilaspur">Bilaspur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_chandigarh">Chandigarh</a></p>	
        <p class="sl-left-menu-pad"><a href="/stores_chennai">Chennai</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_coimbatore">Coimbatore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_dehradun">Dehradun</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_delhi">Delhi &amp; NCR</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_dimapur">Dimapur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_goa">Goa</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_guwahati">Guwahati</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_hyderabad">Hyderabad</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_indore">Indore</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_jaipur">Jaipur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_jalandhar">Jalandhar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_jammu">Jammu</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_kanpur">Kanpur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_karnal">Karnal</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_kochi">Kochi</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_kolkata">Kolkata</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_lucknow">Lucknow</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_ludhiana">Ludhiana</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_mumbai">Mumbai</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_nellore">Nellore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_panchkula">Panchkula</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_panipat">Panipat</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_patiala">Patiala</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_pune">Pune</a></p>

        <p class="sl-left-menu-pad"><a href="/stores_puri">Puri</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_raipur">Raipur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_rajkot">Rajkot</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_surat">Surat</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_vadodra">Vadodra</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_varanasi">Varanasi</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_vijaywada">Vijaywada</a></p>
      	<p class="sl-left-menu-pad select"><a href="/Openingsoon">Opening Soon</p>
	  	<p><a class="thickbox" title="" href="storegallery_fcuk.html?keepThis=true&amp;TB_iframe=true&amp;height=415&amp;width=600"><span class="gallery">View Our Store Gallery</span></a></p>
      <p><a href="view_map"><span class="gallery">View Map</span></a></p>
    </div>
<div class="rightstore">
      <div class="storeheading">Agra</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
 <div class="white">
        <div class="storename">Bachoomal Collection
        <br>
        </div>
        <div class="storeAddress">Bachoomal Collection <br>
								  M.G. Road<br>
								  Opposite Anjna Cinema<br>
								  Agra - 282001

 </div>
 
        <div class="storeContact"> +91 562 2154504 </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>