    
<div class="rightstore">
      <div class="storeheading">Amritsar</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
      <div class="white">
        <div class="storename">AlphaOne<br>
                               (Exclusive Brand Store)</div>
        <div class="storeAddress">AlphaOne<br>
								  Fashion NU<br>
								  Ground Floor<br>
								  Shop no 33<br>
								  MBM Farms<br>
								  Main GT Road<br>
								  Amritsar<br>
						  		  Punjab - 143001</div>
 
        <div class="storeContact">+91 183 506 3232</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
      
      <div class="lightgrey">
        <div class="storename">Kapsons   Amritsar</div>
        <div class="storeAddress">Kapsons Fashion <br>
                        48 Mall   Road<br>
                        Amritsar - 143001                      </div>
 
        <div class="storeContact">+91 85588 12040</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>