    
<div class="rightstore">
      <div class="storeheading">Bangalore</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
     <!-- <div class="white">
        <div class="storename">Shoppers   Stop</div>
        <div class="storeAddress">Shoppers   Stop<br />
                        N.S.Palya<br />
                        Bannerghatta Road<br />
                        Bangalore - 560076                        </div>
 
        <div class="storeContact"> +91 96205 44454</div>
        <div class="clear"></div>
        </div>-->
        
<div class="white">
        <div class="storename">Mantri Square Mall<br>
                              (Exclusive Brand Store)
        </div>
        <div class="storeAddress">Mantri Square Mall<br>
                                  UG-12, Upper Ground Floor<br> 
                                  Sampige Road<br>
                                  Malleswaram<br>
                                  Bangalore - 560 003
         </div>
        <div class="storeContact">+91 80 3016 0104</div>
        <div class="clear"></div>
</div>
      
<div class="lightgrey">
        <div class="storename">Phoenix Marketcity<br>
                               (Exclusive Brand Store)
        </div>
        <div class="storeAddress">Phoenix Marketcity<br>
                                  Plot no 9,10,11a, 12<br> 
                                  Dyavasandra Phase-II Industrial Area<br>
                                  Nr. Krishnarajapuram Flyover<br>
                                  Mahadevpura<br>
                                  Bangalore - 560048
        </div>
        <div class="storeContact">+91 80 6726 6057</div>
        <div class="clear"></div>
</div>
      
<div class="white">
        <div class="storename">Bangalore International<br>Airport
        </div>
        <div class="storeAddress">Bangalore International Airport<br>
                                  Departure Lounge<br>
                                  Shoppers Stop - La Moda<br>
                                  Devanhalli Taluk<br>
                                  Bangalore - 562110</div>
        <div class="storeContact">+91 93530 07101</div>
        <div class="clear"></div>
</div>
	  
<div class="lightgrey">
        <div class="storename">Forum Value Mall<br>
                               (Outlet Store)
        </div>
        <div class="storeAddress">Forum Value Mall<br>
								  No.62<br>
								  Whitefield Main Road<br>
								  Whitefield<br>
								  Bangalore - 560066</div>
        <div class="storeContact">+91 91643 99551</div>
        <div class="clear"></div>
</div>      
      
      
<div class="white">
        <div class="storename">Shoppers   Stop
        </div>
        <div class="storeAddress">Shoppers Stop<br>
                                  Garuda Mall<br>
                                  Magrath Road<br> 
                                  Ashok Nagar<br> 
                                  Bangalore - 560025</div>
        <div class="storeContact">+91 93530 07103</div>
        <div class="clear"></div>
</div>
      
      
<div class="lightgrey">
        <div class="storename">Shoppers Stop
        </div>
        <div class="storeAddress">Shoppers Stop<br>
                                  Mantri Mall<br>
                                  N.S.Palya<br>
                                  Bannerghatta Road<br>
                                  Bangalore - 560076 
        </div>
        <div class="storeContact">+91 93798 43942</div>
        <div class="clear"></div>
</div>
	  	  
	  <div class="clear"></div>
      
      <div class="white">
        <div class="storename">Central
        </div>
        <div class="storeAddress">French Connection<br>
Bangalore Central-2<br>
Plot No.45/1, 45/2<br>
45th Cross<br> 
J.P.Nagar<br> 
2nd Phase<br> 
Bangalore- 560069
        </div>
        <div class="storeContact">+91 97385 86642
</div>
        <div class="clear"></div>
</div>
	  	  
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>