  
<div class="rightstore">
      <div class="storeheading">Bhopal</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">DB City Mall<br></div>
        <div class="storeAddress">DB City Mall<br>
        						My Shoppe<br>
                               Ground Floor<br>
                               Arera Hill <br>
                               Bhopal - 462011
 <br>

</div>
 
        <div class="storeContact">+91 88177 41820  </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>