   
<div class="rightstore">
      <div class="storeheading">Bhubaneswar</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">All That Jazz<br></div>
        <div class="storeAddress">All That Jazz<br>
								  Plot No - 437 patia<br>
								  Beside Idea Office<br>
                                  Jaydev Vihar<br>
                                  Bhubaneswar - 751016<br>
								  Odisha

</div>
 
        <div class="storeContact"> +91 73810 93005 

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses av