<div class="rightstore">
      <div class="storeheading">Bilaspur</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
 <div class="white">
        <div class="storename">Rama Magneto Mall
        <br>(Exclusive Brand Store)
        </div>
        <div class="storeAddress">Shop No.-G 8<br>
        							Rama Magneto Mall<br>
        							Din Dayal Upadhyay Chowk<br>
									Srikant Verma Marg<br>
									Bilaspur (C.G) ?492001</div>
 
        <div class="storeContact"> +91 7752 422207 </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>