<div class="rightstore">
      <div class="storeheading">Chandigarh</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	   <div class="white">
        <div class="storename">
 
 Sector 17C <br>(Exclusive Brand Store)<!--<span class="astric">*</span>--> </div>
        <div class="storeAddress">Kapsons Fashion <br> 
        SCO 90<br>
        Sector 17C<br>
        Chandigarh - 160017</div>
        <div class="storeContact">+91 172 272 0061</div>
        <div class="clear"></div>
      </div>
      
	  
	  <div class="lightgrey">
        <div class="storename">
 
 Kapsons Fashion <!--<span class="astric">*</span>--> </div>
        <div class="storeAddress">Kapsons Fashion <br> 
        SCO 104-105<br>
        Sector 17C<br>
        Chandigarh - 160017</div>
        <div class="storeContact">+91 93170 08202</div>
        <div class="clear"></div>
      </div>
      <div class="white">
        <div class="storename">Kapsons Exclusive<br>
        (Womenswear store)<!--<span class="astric">*</span>--> </div>
        <div class="storeAddress">French Connection <br> 
        S.C.O-110/111<br>
        Sector-17 C<br>
        Chandigarh - 160017</div>
        <div class="storeContact">+91 964 691 4586</div>
        <div class="clear"></div>
      </div>
	  
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>