<div class="rightstore">
      <div class="storeheading">Gandhidham</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">S Jivraj<br></div>
        <div class="storeAddress">S Jivraj<br>
								  Shop no 108/9/10<br>
								  Siddhivinayak Complex<br>
                                  Tagore Road<br>
								  Gandhidham - 370201

</div>
 
        <div class="storeContact"> +91 28 3665 4062 </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>