<div class="rightstore">
      <div class="storeheading">Goa</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
        
      </div><div class="white">
        <div class="storename">Saga <br></div>
        <div class="storeAddress">Saga <br>
								  Opposite Dona Sylvia<br>
                                  Khandi Morbor Road<br>
								  Cavelassim Salcete<br> 
								  Goa - 403731
</div>
 
        <div class="storeContact">+91 832 2871 239

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!-- <div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>