<div class="rightstore">
      <div class="storeheading">Guwahati</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Sohum Emporio</div>
        <div class="storeAddress">Sohum Emporio<br>
        ABC<br>
                                  Beside S Rajiv Bhawan<br>
                                  G.S Road<br>
                                  Guwahati. 781005
 


</div>
 
        <div class="storeContact"></div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>