<div class="rightstore">
      <div class="storeheading">Indore</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
        <div class="storename"> C-21 Mall<!--<span class="astric">*</span>--><br>(Exclusive Brand Store) </div>
        <div class="storeAddress">C-21 Mall<br>
        Shop no. 1A, Ground Floor<br>
		A.B. Road<br>
		Indore - 452001<br>
		Madhya Pradesh
		</div>

        <div class="storeContact">+91 731 4056795</div>
        <div class="clear"></div>
        </div>
        
        <div class="lightgrey">
        <div class="storename"> U Turn
<!--<span class="astric">*</span>--></div>
        <div class="storeAddress">French Connection<br>
U Turn<br>
G-4 Shagun Arcade<br>
Vijay Nagar<br>
Square AB Road<br>
Indore ? 452001
		</div>

        <div class="storeContact">+91 731 405 6706
</div>
        <div class="clear"></div>
      </div>
      
      
      	<!--<div class="lightgrey">
        <div class="storename"> Phoenix Market City <span class="astric">*</span>(Exclusive Brand Store)</div>
        <div class="storeAddress">Phoenix Market City <br />
        UG-071, Upper Ground floor<br /> 
        Phoenix Market City Mall<br />
        Near Hyatt Hotel<br />
        Viman Nagar<br />
        Pune - 411014</div>
        <div class="storeContact">+91 20 30950228</div>
        <div class="clear"></div>
      </div>-->
	  
      
      
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>