<div class="rightstore">
      <div class="storeheading">Jaipur</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <div class="white">
        <div class="storename">
		World Trade Park<br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">World Trade Park<br>
        						  LG 12,13 Block B <br>
								  World Trade Park<br>
								  JLN Road Malviya Nagar<br>
								  Jaipur - 32017<br>
								        </div>
        <div class="storeContact">+91 141 278019</div>
        <div class="clear"></div>
      </div>
      
  
	  
	   






 
	 
	  
	 
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>