<div class="rightstore">
      <div class="storeheading">Jalandhar</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <div class="white">
        <div class="storename">
 MBD Neopolis Mall <!--<span class="astric">*</span> --></div>
        <div class="storeAddress">French Connection<br>
         Shop No 2<br> 
        Ground Floor<br> 
        BMC Chowk<br>
        Jalandhar - 144001
        </div>
        <div class="storeContact">+91 18150 02900</div>
        <div class="clear"></div>
      </div>
	  
	  <div class="lightgrey">
        <div class="storename">
 Kapsons Fashion <!--<span class="astric">*</span> --></div>
        <div class="storeAddress">Kapsons Fashion <br>
         Shop No.194 
        R<br> 
        Model Town<br> 
        Jalandhar - 144003</div>
        <div class="storeContact">+91 93170 86893</div>
        <div class="clear"></div>
      </div>
	  
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>