<div class="rightstore">
      <div class="storeheading">Jammu</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Kapsons   Jammu</div>
        <div class="storeAddress">Kapsons <br>
                            Apsara Theatre<br> 
                               Gandhinagar<br> 
                            Jammu City - 180004 
              </div>
 
        <div class="storeContact">+91 9018826459 </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>