<div class="rightstore">
      <div class="storeheading">Karnal</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Kapsons Fashion</div>
        <div class="storeAddress">Kapsons Fashion<br>
                             	  Shop No 970-971<br>
                          	      Opp Post Office<br> 
                        	       Karnal - 132001

</div>
 
        <div class="storeContact">+91 8558812043</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>