<div class="rightstore">
      <div class="storeheading">Kochi</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
        <div class="storename">MG Road <!--<span class="astric">*</span>--><br>(Exclusive Brand Store) </div>
        <div class="storeAddress">
        Kalangot Towers<br>
		Ground Floor<br>
		MG Road<br>
		North End<br>
		Kochi 682035</div>

        <div class="storeContact">+91 484 2354 441</div>
        <div class="clear"></div>
      </div>
      
      	  <!--<div class="lightgrey">
        <div class="storename"> Fashion House <!--<span class="astric">*</span>--></div>