<div class="rightstore">
      <div class="storeheading">Kolkata</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
     <!-- <div class="white">
        <div class="storename">Shoppers   Stop</div>
        <div class="storeAddress">Shoppers   Stop<br />
                        N.S.Palya<br />
                        Bannerghatta Road<br />
                        Bangalore - 560076                        </div>
 
        <div class="storeContact"> +91 96205 44454</div>
        <div class="clear"></div>
        </div>-->
      
        <div class="white">
        <div class="storename">South City Mall <br>(Exclusive Brand Store)</div>
        <div class="storeAddress">French Connection<br>
        South City Mall<br>
        S-024, South City Mall<br> 
        Prince Anwar Shah Road<br> 
        Kolkata - 700068</div>
        <div class="storeContact">+91 33 4064 3441</div>
        <div class="clear"></div>
      </div>
      
      <div class="lightgrey">
        <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop
								  Forum Mall<br>
								  10/3 Lala Lajpat Rai Road<br>
								  (Elgin Road)<br>
								  Kolkata - 700020</div>
        <div class="storeContact">+91 33 2283 0434</div>
        <div class="clear"></div>
      </div>
      <div class="white">
        <div class="storename">Sumangal</div>
        <div class="storeAddress">Sumangal<br>
								  French Connection<br>
								  Pic Departmentals Pvt. Ltd.<br>
								  3 &amp; 4 Lindsay Street<br>
								  Kolkata- 700087
                                  </div>
        <div class="storeContact"> +91 33 2249 7317 </div>
        <div class="clear"></div>
      </div>
      
      
	  
	  
	  <!--<div class="lightgrey">
        <div class="storename">
  Bangalore International Airport</div>
        <div class="storeAddress">       Bangalore International Airport<br />
          Departure Lounge<br />
          Shoppers Stop - La Moda<br />
          Devanhalli Taluk<br />
        Bangalore - 562110</div>
        <div class="storeContact">+91 80 3247 9647</div>
        <div class="clear"></div>
      </div>-->
	  
	  
	  
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>