<div class="rightstore">
      <div class="storeheading">Ludhiana</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
       <div class="white">
        <div class="storename">Silver Arc Mall<br>(Exclusive Brand Store)</div>
        <div class="storeAddress">Silver Arc Mall<br>
								  G-01, Aarti cinema chowk<br>
 								  Ferozpur Road<br>
							      Ludhiana 141001

</div>
 
        <div class="storeContact">+91 161 4612 327</div>
        <div class="clear"></div>
      </div>
      
      <div class="lightgrey">
        <div class="storename">MBD Mall <br>(Exclusive Brand Store)</div>
        <div class="storeAddress">French Connection<br>
        Shop No. G-14<br>
Ground Floor<br>
MBD Neopolis Mall<br>
Ferozepur Road<br>
Ludhiana - 141 012<br>
Punjab

</div>
 
        <div class="storeContact">+91 161 504 8076 </div>
        <div class="clear"></div>
      </div>
      
      
      <div class="white">
        <div class="storename">Kapsons   Fashion</div>
        <div class="storeAddress">Kapsons Fashion<br>
        Ansal Plaza Mall <br>
                        Ferozpur Road<br>
                        Ludhiana - 141001</div>
 
        <div class="storeContact">+91 93170 86891 </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>