<div class="rightstore">
      <div class="storeheading">Coming Soon </div>
      <div class="storetitle">
        <div class="storename">City</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  
	  <!-- <div class="white">
        <div class="storename">Ambience Mall </div>
        <div class="storeAddress">Ambience Mall<br />
                                  Vasant Kunj <br />
                                 New Delhi</div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div> 
      </div> -->
      
      
      	  <!--<div class="lightgrey">
        <div class="storename">Chennai Express</div>
        <div class="storeAddress">Chennai Express<br />
                                  Shop no. S001C<br />
                                  Express Estates<br />
                                  Club House Road<br />
                                  Mount Road<br />
                                  Chennai<br />
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
	  
	<!-- <div class="lightgrey">
        <div class="storename">MBD Neopolis Mall</div>
        <div class="storeAddress">MBD Neopolis Mall<br />
                                  Ferozpur Road<br />
                                  Ludhiana<br />
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
      
      	 <!-- <div class="lightgrey">
        <div class="storename">Pacific Mall</div>
        <div class="storeAddress">Pacific Mall <br />
                                  Main Najafgarh Road <br />
                                  New Delhi<br />
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
            	 <!--<div class="white">
        <div class="storename">Hyderabad </div>
        <div class="storeAddress">GVK One<br />
        						  Hyderabad
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
       <!--<div class="white">
        <div class="storename">Mumbai</div>
        <div class="storeAddress">Phoenix Market City<br />
                                  LBS Marg <br />
                                  Kurla<br />
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
        <!-- <div class="lightgrey">
        <div class="storename">Indore</div>
        <div class="storeAddress">Shop no. 1A<br />
                                  Ground Floor<br />
                                  C-21 Mall<br />
                                  A.B. Road<br />
                                  Indore (MP)
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
       <!--div class="white">
        <div class="storename">Jaipur</div>
        <div class="storeAddress">World Trade Park<br>
                                  Jaipur
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div-->
      
         <!-- <div class="white">
        <div class="storename">Kanpur</div>
        <div class="storeAddress">Z Square Mall<br />
                                   Kanpur
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
          <!--<div class="lightgrey">
        <div class="storename">Lucknow</div>
        <div class="storeAddress">Wardrobe
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
     <!-- <div class="lightgrey">
        <div class="storename">Guwahati</div>
        <div class="storeAddress"> Swagato Square<br />
                                   GS road<br />
                                   ABC
                                  </div>
 
        <div class="storeContact"> </div>
        <div class="clear"></div>
      </div>-->
      
<div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>