<div class="rightstore">
      <div class="storeheading">Pune</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
      <div class="storename"> Phoenix Marketcity <!--<span class="astric">*</span>-->(Exclusive Brand Store)</div>
        <div class="storeAddress">Phoenix Market City <br>
        						  UG-071, Upper Ground floor<br> 
        						  Phoenix Market City Mall<br>
        						  Near Hyatt Hotel<br>
        					      Viman Nagar<br>
        						  Pune - 411014</div>
        <div class="storeContact">+91 20 30950228</div>
        <div class="clear"></div>
        </div>
 
      
      <div class="lightgrey">
        <div class="storename">Koregaon Plaza Mall<!--<span class="astric">*</span>-->(Exclusive Brand Store)
        </div>
        <div class="storeAddress">Koregaon Plaza Mall<br>
        						  Shop - GF 3A<br> 
                				  North Main Road<br>
        						  Pune - 411001</div>
        
        <div class="storeContact">+91 20 3053 0116</div>
        <div class="clear"></div>
      </div>
      
      
      
      	<div class="white">
        <div class="storename"> Central Mall<!--<span class="astric">*</span>--></div>
        <div class="storeAddress">Central Mall<br>
        						  Ganesh- Khind<br>
								  Near E - Square<br>
								  Opp. Agriculture College<br>
								  Pune - 411007 	</div>
        <div class="storeContact">+91 20 6500 2819</div>
        <div class="clear"></div>
      </div>
      
      <!--<div class="lightgrey">
        <div class="storename">Shoppers Stop<!--<span class="astric">*</span></div>
        <div class="storeAddress">Shoppers Stop<br />
        Koregaon Park Plaza<br />
		Ground floor<br />
		Shop No GF 3 A<br />
		North main road<br />
		Koregaon Park<br />
		Pune - 411001 </div>
        
        <div class="storeContact"></div>
        <div class="clear"></div>
      </div>-->
	  
      
      
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>