<div class="rightstore">
      <div class="storeheading">Puri</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">All That Jazz</div>
        <div class="storeAddress">All That Jazz<br>
								  Opp Police Reserve<br>
				                  VIP Road<br>
								  Near Hero Honda Showroom<br>
							      Puri - 752002

</div>
 
        <div class="storeContact">+91 92380 33452</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>