<div class="rightstore">
      <div class="storeheading">Surat</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
	  <div class="white">
        <div class="storename">B.More</div>
        <div class="storeAddress">Dharam Palace<br>
								  Near Surat People Bank<br>
								  Opp. Parle Point Place<br>
								  End of Ghod Dod Road<br>
							  	  Surat - 395007 	

		</div>
 
        <div class="storeContact">+91 261 3209 077</div>
        <div class="clear"></div>
      </div>
	  <div class="clear"></div>
	  <div class="lightgrey">
		<div class="storename">Virtuous Mall<br>(Exclusive Brand Store)</div>
		<div class="storeAddress">French Connection
			GF 24A, Virtuous Mall,<br>
			Udha Magdalla Road,<br>
			Surat - 395007 
		</div>
		<div class="storeContact">+91 261 6519944</div>
		<div class="clear"></div>
	  </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
 