<div class="rightstore">
      <div class="storeheading">Varanasi</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
        
      </div><div class="white">
        <div class="storename">Kambalghar Exclusive<br></div>
        <div class="storeAddress">Kambalghar Exclusive<br>
								  C 27/277 B Maldahiya<br>
								  Varanasi - 221001



</div>
 
        <div class="storeContact"> +91 542 2202502 

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>