<?php	$idval=$this->getRequest()->getParam('id'); 
			if($idval)
			{
			$resource = Mage::getSingleton('core/resource');
			$read = $resource->getConnection('core_read');
			$query1 = "SELECT * FROM findaddress where id=$idval limit 0,5";
			$result1=$read->query($query1);
			$postcodeadd = $result1->fetchAll();
			}
		//	print_r($postcodeadd);
?>
<div class="billing_address_content">
<?php if($this->getTitle()): ?>
<!--div class="page-title">
    <h1><?php //echo $this->getTitle() ?></h1>
</div-->
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
   
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <h1 class="acountTitle">YOUR BILLING ADDRESS</h1>
    
	<p>Fields marked with an * are mandatory and must be completed.</p>
        <ul class="form-list" >
           <div class="addressDiv" style="visibility:hidden;height:0px; margin:0px;">
                <?php echo $this->getNameBlockHtml() ?>
			</div>	
				<?php $userinfo=Mage::getSingleton('customer/session')->getCustomer(); 
				//echo '<pre>';print_r($userinfo->getData());
				?>
				
           <div class="addressDiv" style="visibility:hidden;height:0px; margin:0px;">
                <div class="addressName"><?php echo $this->__('Company') ?></div>
                <div class="addressinputArea">
                    <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </div>
			</div>
			
			<div class="addressDiv" style="visibility:hidden;height:0px; margin:0px;">                            
				<div class="addressName"><?php echo $this->__('Telephone') ?><sup>*</sup></div>
				<div class="addressinputArea">
					<input type="text" name="telephone" value="<?php echo $userinfo->getData('telephoneno'); ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
				</div>
            </div>
			
            <div class="addressDiv" style="visibility:hidden;height:0px;">
                <div class="addressName"><?php echo $this->__('Fax') ?></div>
                <div class="addressinputArea">
                        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                    </div>
            </div>
          

   
   
        <!--h2 class="legend"><?php //echo $this->__('Address') ?></h2-->
        <ul class="form-list">
		    <div class="addressForm">
			<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
           
            <div class="addressDiv">
                <div class="addressName"><?php echo $this->__('Address') ?><em>*</em></div>
                <div class="addressinputArea">
                    <input type="text" name="street[]" value="<?php echo $postcodeadd[0]['street']; ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="inputSty input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
          
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <div class="addressDiv">
				<div class="addressName">&nbsp;</div>
				<div class="addressinputArea">
					<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="inputSty input-text <?php echo $_streetValidationClass ?>" />
				</div>
			</div>
            
           
        <?php endfor; ?>
            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <li class="wide">
                <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                <div class="input-box">
                    <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="inputSty input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </li>
            <?php endif; ?>
            
               <div class="addressDiv">
                    <div class="addressName"><?php echo $this->__('City') ?><sup>*</sup></div>
                    <div class="addressinputArea">
                        <input type="text" name="city" value="<?php echo $postcodeadd[0]['city']; ?>"  title="<?php echo $this->__('City') ?>" class="inputSty input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>
              
                   <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('State/Province') ?><sup>*</sup></DIV>
                    <div class="addressinputArea">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $postcodeadd[0]['state']; ?>"  title="<?php echo $this->__('State/Province') ?>" class="inputSty input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
           
            <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('Postcode') ?><sup>*</sup></div>
                    <div class="addressinputArea">
                        <input type="text" name="postcode" value="<?php echo $postcodeadd[0]['postcode']; ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="inputSty input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('Country') ?><sup>*</sup></div>
                    <div class="addressinputArea">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            
			 <input type="hidden" name="default_billing" value="1" />
			 <?php 
            /* <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif; ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </li> */
			?>
        </ul>
  
    <!--div class="buttons-set">
	 <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </div-->   
        <?php $userid=$userinfo->getData('default_billing'); ?>
        <div class="addressDiv" style="*margin-bottom:20px;  margin:20px 0">
		<span class="back-link">
		<a href="<?php echo $this->escapeUrl($this->getBaseUrl().'customer/address/edit/id/'.$userid)?>">
		<span class="goBackBtn">Go back</span>
        </a>
        </span>
        <input type="submit" title="" value="Continue" class="continueBtn" />
   </div>
   
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>
//var countryselected='<?php echo $this->getRequest()->getParam('country_id')?>';
//alert(countryselected)
jQuery('select[name="country_id"]').find('option[value="<?php echo $this->getRequest()->getParam('country_id')?>"]').attr("selected",true);
</script>
