
<div class="footer">
<div  class="footer_content_container close" style="height:200px; display:none;">
	
 	<div class="footer_content">
 		<div id="siteFooter" class="show_desktop">
 			<div id="footer_bar">
 				<div class="container container_24">

		              <div id="footerNav_container_bar">
		                <ul class="clearfix">
		                  <li><span class="footHdr">Shop Online</span></li>
		                  <li class="footerNav_divide"><span class="footHdr">|</span></li>
		                  <li><span class="footHdr">About FC</span></li>
		                  <li class="footerNav_divide"><span class="footHdr">|</span></li>
		                  <li><span class="footHdr">Company</span></li>
		                  <li class="footerNav_divide"><span class="footHdr">|</span></li>
		                  <li class="last" style="border:0;"><span class="footHdr">More</span></li>
		                </ul>
		              </div>

		              <div id="socialNav_container">
			            <nav id="socialNav">
			              <ul class="clearfix">
			                <li>
			                  <span class="footHdr">Follow Us</span>
			                  <ul class="clearfix">
			                    <!-- Facebook -->
			                    <li><a class="facebook" target="_blank" href="https://www.facebook.com/frenchconnectionindia?ref=ts">Facebook</a></li>
			                    <!-- Twitter -->
			                    <li><a class="twitter" target="_blank" href="https://twitter.com/fcuk_india">Twitter</a></li>
			                    <!-- Google + -->
			                    <li><a class="google" target="_blank" href="http://plus.google.com/111297161320260268905/posts">Google+</a></li>
			                    <!-- Pinterest -->
			                    <li><a class="pinterest" target="_blank" href="http://www.pinterest.com/fcukindia/">Pinterest</a></li>
			                    <!-- Youtube -->
			                    <li><a class="youtube_footer" target="_blank" href="http://www.youtube.com/user/frenchconnectionIN">Youtube</a></li>
			                    <!-- Instagram -->
			                    <li><a class="instagram" target="_blank" href="http://www.instagram.com/frenchconnection_in">instagram</a></li>
			                    <!-- Blog -->
			                    <li><a class="blog" target="_blank" href="http://911fashion.frenchconnection.in">blog</a></li>
			                  </ul>
			                </li>
			              </ul>
			            </nav>
			          </div>

		              <!-- <div id="socialNav_container">
		                <nav id="socialNav">
		                  <ul class="clearfix">
		                    <li>
		                    <span class="footHdr">Follow Us</span>
		                      <ul class="clearfix">
		                        <li><a href="https://www.facebook.com/frenchconnectionindia?ref=ts" target="_blank" class="facebook">Facebook</a></li>
		                        <li><a href="https://twitter.com/fcuk_india" target="_blank" class="twitter">Twitter</a></li>
		                        <?php //echo <li><a href="https://twitter.com/fcuk_india" target="_blank" class="google">Google</a></li>?>
		                        <li><a href="http://www.pinterest.com/fcukindia/" target="_blank" class="pinterest">Pinterest</a></li>
		                        <li><a href="http://www.youtube.com/user/frenchconnectionIN" target="_blank" class="youtube">Youtube</a></li>
		                        <li><a href="http://www.instagram.com/frenchconnection_in" target="_blank" class="instagram">Instagram</a></li>
		                        <li><a href="http://911fashion.frenchconnection.in" target="_blank" class="blog">Blog</a></li>		                     
		                      </ul>
		                    </li>
		                  </ul>
		                </nav>
		              </div> -->

		              <div class="clear"></div>

	            </div>
 			</div>

 			<div class="container container_24">

	            <div id="footerNav_container">
	              <nav id="footerNav" role="navigation">
	                <ul class="clearfix">
	                  <li>
	                    <ul>
	                      <li><a href="<?php echo $this->getUrl('woman.html')?>" title="Woman">Woman</a></li>
	                      <li><a href="<?php echo $this->getUrl('man.html')?>" title="Man">Man</a></li>
	                      <!--<li><a href="<?php //echo $this->getUrl('sale.html')?>" title="Sale">Sale</a></li>
	                      <li><a href="<?php //echo $this->getUrl('#')?>" title="Outlet">Outlet</a></li>
	                      <li><a href="<?php //echo $this->getUrl('#')?>" title="Subscribe">Subscribe</a></li>-->
	                 
	                    </ul>
	                  </li>
	                  <li>
	                    <ul>
	                      <!--<li><a href="<?php //echo $this->getUrl('about_fcuk_india')?>" title="FC India">FC India</a></li>-->
	                      <li><a href="<?php echo $this->getUrl().'fashion-is-our-business'?>" target="_blank" title="About French Connection">About FCUK</a></li>
	                      <li><a href="<?php echo $this->getUrl('how-to-order')?>" title="Help">Help</a></li>
	                      <li><a href="<?php echo $this->getUrl('contact-us')?>" title="Contact Us">Contact Us</a></li>
	                      <li><a href="<?php echo $this->getUrl('shipping-delivery')?>" title="Delivery">Delivery</a></li>
		 				 <li><a href="<?php echo $this->getUrl('cancellation-refund')?>" title="Cancellation Refund Policy">Cancellation Policy</a></li>
		 				 <!--<li><a href="<?php //echo $this->getUrl('#')?>" title="Returns">Returns</a></li>-->
	                    </ul>
	                  </li>
	                  <li>
	                    <ul>
	                      <!--<li><a href="<?php //echo $this->getBaseUrl('#');?>" title="Investor Relations">Investor Relations</a></li>-->
	                      <li><a href="<?php echo $this->getBaseUrl()."press-home"?>" title="Press">Press</a></li>
						  <li><a href="<?php echo $this->getUrl('careers')?>" title="Careers">Careers</a></li>
						  <!--<li><a href="<?php //echo $this->getUrl('#')?>" title="Licensing">Licensing</a></li>-->
	                    </ul>
	                  </li>
	                  <li class="last" style="border:0;">
	                    <ul>
	                      <li><a href="<?php echo $this->getUrl('privacy-policy')?>" title="Privacy Policy">Privacy Policy</a></li>
						  <li><a href="<?php echo $this->getUrl('termsconditions')?>" target="_blank" title="Terms &amp; Conditions">Terms &amp; Conditions</a></li>
						  <li><a href="<?php echo $this->getUrl('storelocator')?>" title="Store Locator">Store Locator</a></li>
						  <li><a href="<?php echo $this->getBaseUrl().'sitemap'?>" title="sitemap">Site Map</a></li>	
	                    </ul>
	                  </li>
	                </ul>
	              </nav>
	            </div>

	            <!-- <div class="newsletter-container">
	            	<a href="<?php //echo $this->getUrl('about_you');?>" class="newsletter">
	            		<span id="head">SIGN UP TO OUR NEWSLETTER</span>
	            		<span id="text">Be the first to know the latest style news</span>
	            		<span id="sign">sign up</span>
	            	</a>
	            </div> -->

	            <div class="footer_email_sign_up show_desktop">
	               <div class="footer_newsletter_link_title">Email sign up</div>
	                <form action="/about_you" method="POST" id="footer_newsletter_link" class="show_desktop">
	                  <input type="hidden" name="srce" value="ONLINE_FOOTERBOX">
	                  <input type="text" name="email" placeholder="email address" class="email_bar">
	                  <div class="gender_option">
	                    <input type="submit" name="gender" value="Woman" class="footer_newsletter_link_cta first_gender">
	                    <input type="submit" name="gender" value="Man" class="footer_newsletter_link_cta last_gender">
	                  </div>
	                </form>
	            </div>

            <div class="clear"></div>

          </div>
		</div>
	</div>
	                     
  </div>
  <div class="logo_container">
	  <div class="logo_footer">
	  	<a class="footer_content_tab">more +</a>
	    <a class="logo-content" href="/">
	      <img class="svg_logo" src="<?php echo $this->getSkinUrl('images/kishan/french-connection-logo.png') ?>">
	    </a>
	  </div>

  </div>
</div>
	
      
<script>
jQuery(document).ready(function($){
  	$(".footer_content_tab").click(function(){
    if($(".footer_content_container").hasClass("open")){
      hideFooter();
    }
    if($(".footer_content_container").hasClass("close")){     
      showFooter();
    }

    /* code to create fancybox */
    // $("a.fancybox").fancybox({
    //   "padding":0,
    //   "overlayColor": "#000",
    //   "overlayOpacity": 0.7,
    //   "hideOnOverlayClick": true,
    //   "width": 800,
    //   "height": 500,
    //   "autoResize": true 
    // });


  });

  function showFooter(){
	 
	 $(".footer_content_container").removeClass("close");
	 $(".footer_content_container").addClass("open");
	 $(".footer_content_tab").html("close -");
	 $(".footer_content_container").stop(true, true).slideDown(300);
	 $(".container_24").show();
  }
  function hideFooter(){
	 
   	 $(".footer_content_container").stop(true, true).slideUp(300, function(){
   	 	$(".footer_content_container").removeClass("open");
	 	$(".footer_content_container").addClass("close");	
	 	$(".footer_content_tab").html("more +");
   	 });
	 
	 
  }
// jQuery(document).mouseup(function (e){
//     var container = jQuery(".footer_content_container");
//     if (container.has(e.target).length === 0){
//       hideFooter();
//     }
  // });


});
</script>


 