<style>

.category-man-landing {
    background-image: url("http://fcuk.iksulabeta.com/skin/frontend/fcuk/default/images/women-main-cat-bg.jpg");
    background-position: center 24px;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}
 .header-bg-1, .category-woman .header-bg-1, .category-man .header-bg-1 {
    background-image: url("http://fcuk.iksulabeta.com/skin/frontend/fcuk/default/images/fcukwrapper.jpg");
    background-position: left top;
    background-repeat: repeat-x;
    width: 100%;
}

.wrapper {
    background: url("http://fcuk.iksulabeta.com/skin/frontend/fcuk/default/images/fcukwrapper.jpg") repeat-x scroll 0 0 transparent;
    margin: 0;
    padding: 0;
}

.header-bg{
    background-color: rgba(255, 255, 255, 0.6);
    width: 100%;
}
</style>


<div class="womenCatTextLinkArea"><a href="#">shop <span>dresses</span></a>
 <a href="#">shop <span>tops</span></a> <a href="#">shop <span>coats &amp; jackets</span></a> 
 <a href="#">shop <span>jeans</span></a> <br/><a href="#">shop <span>knitwear</span></a> 
 <a href="#">shop <span>trousers &amp; leggings</span></a> <a href="#">shop <span>accessories</span></a>
 <a class="shopwNowBtn" href="#">&nbsp;</a></div>
<div class="womenCatArea">
<div class="womenCatwindow1"><a href="#"><img class="transeff" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Woman/women-main-cat-bg-1.jpg" alt="" /></a>
	<div class="womenCatwindow5">
		<div class="womenCatwindow3"><a href="#"><img class="transeff" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Woman/women-main-cat-bg-3.jpg" alt="" /></a></div>
		<div class="womenCatwindow4"><a href="#"><img class="transeff" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Woman/women-main-cat-bg-4.jpg" alt="" /></a></div>
	</div>
</div>
<div class="womenCatwindow2"><a href="#"><img class="transeff" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Woman/women-main-cat-bg-2.jpg" alt="" /></a></div>
<div class="copyright_text">Established in 1972, French Connection is a world-renowned fashion brand famed for its high-design approach. In addition to producing seasonal <a href="#">menswear</a> and <a href="#">womenswear</a> clothing collections, French Connection also offers a <a href="#">homeware</a> line, <a href="#">footwear</a> and <a href="#">accessories</a>.</div>
</div>