<?php echo "hi";
$_product=Mage::getModel('catalog/product')->loadByAttribute('sku','SSAL9');


?>
<div class="product-collateral">
               				
        <ul class="tabs">

        
                                    <li class="first active" id="product_tabs_description_tabbed"><a href="javascript:void(0)">DESCRIPTION</a></li>
	   	                 
                                    <li id="product_tabs_review_tabbed" class=""><a href="javascript:void(0)">Reviews</a></li>
	   	                 
        
</ul>
<div class="padder">

                        <div id="product_tabs_description_tabbed_contents" style="">
				    <div class="std">
		<h4 class="tabheading">WEBBING DRILL BELT</h4>
		<h4 class="tabheading pricetab">		

                
    <div class="price-box">
	                                
                    <p class="old-price">
                <span class="price-label"></span>
                <span id="old-price-1116" class="price">
                    Rs. 1,699.00                </span>
            </p>

                        <p class="special-price">
                <span class="price-label"></span>
								                <span id="product-price-1116" class="price">
                    Rs. 1,189.00                </span>
            </p>
                    
    
        </div>

		</h4>
		<div>Stylecode : TCAF9</div>
		<span>French Connection canvas belt is a sporty, off-duty staple.  <br><br>Webbing Drill Belt has a box-frame buckle and logo tab at length.<br><br>
 * 100% Cotton		
		</span>

		                 <div class="short-description">
                    <div class="std"><p></p></div>
                </div>
                </div>
            </div>
                                <div id="product_tabs_review_tabbed_contents" style="display: none;">
				

<br>


<div class="write_review_heading">Write Your Own Review</div>
<div class="form-add">
        <form id="review-form" method="post" action="http://fcuk.iksulabeta.com/review/product/post/id/1116/">
        <fieldset>
                        <h3 class="youre_reviewing">You're reviewing: <br><span>WEBBING DRILL BELT</span></h3>
                            <h4 class="how_doyou_rate">How do you rate this product? <em class="required">*</em></h4>
                <span id="input-message-box"></span>
                <table id="product-review-table" class="data-table">
                    <colgroup><col>
                    <col width="1">
                    <col width="1">
                    <col width="1">
                    <col width="1">
                    <col width="1">
                    </colgroup><thead>
                        <tr class="first last">
                            <th>&nbsp;</th>
                            <th><span class="nobr">1 star&nbsp;&nbsp;</span></th>
                            <th><span class="nobr">2 stars</span></th>
                            <th><span class="nobr">3 stars</span></th>
                            <th><span class="nobr">4 stars</span></th>
                            <th><span class="nobr">5 stars</span></th>
                        </tr>
                    </thead>
                    <tbody>
                                            <tr class="first odd">
                            <th>Price</th>
                                                    <td class="value"><input type="radio" class="radio" value="11" id="Price_1" name="ratings[3]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="12" id="Price_2" name="ratings[3]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="13" id="Price_3" name="ratings[3]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="14" id="Price_4" name="ratings[3]"></td>
                                                    <td class="value last"><input type="radio" class="radio" value="15" id="Price_5" name="ratings[3]"></td>
                                                </tr>
                                            <tr class="even">
                            <th>Value</th>
                                                    <td class="value"><input type="radio" class="radio" value="6" id="Value_1" name="ratings[2]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="7" id="Value_2" name="ratings[2]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="8" id="Value_3" name="ratings[2]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="9" id="Value_4" name="ratings[2]"></td>
                                                    <td class="value last"><input type="radio" class="radio" value="10" id="Value_5" name="ratings[2]"></td>
                                                </tr>
                                            <tr class="last odd">
                            <th>Quality</th>
                                                    <td class="value"><input type="radio" class="radio" value="1" id="Quality_1" name="ratings[1]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="2" id="Quality_2" name="ratings[1]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="3" id="Quality_3" name="ratings[1]"></td>
                                                    <td class="value"><input type="radio" class="radio" value="4" id="Quality_4" name="ratings[1]"></td>
                                                    <td class="value last"><input type="radio" class="radio" value="5" id="Quality_5" name="ratings[1]"></td>
                                                </tr>
                                        </tbody>
                </table>
                <input type="hidden" value="" class="validate-rating" name="validate_rating">
                <script type="text/javascript">decorateTable('product-review-table')</script>
                            <ul class="form-list">
                    <li>
                        <label class="required" for="nickname_field"><em>*</em>Nickname</label>
                        <div class="input-box">
                            <input type="text" value="" class="input-text required-entry" id="nickname_field" name="nickname">
                        </div>
                    </li>
                    <li>
                        <label class="required" for="summary_field"><em>*</em>Summary of Your Review</label>
                        <div class="input-box">
                            <input type="text" value="" class="input-text required-entry" id="summary_field" name="title">
                        </div>
                    </li>
                    <li>
                        <label class="required" for="review_field"><em>*</em>Review</label>
                        <div class="input-box">
                            <textarea class="required-entry" rows="3" cols="5" id="review_field" name="detail"></textarea>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <!--<div class="buttons-set">
                <button type="submit" title="Submit Review" class="button"><span><span>Submit Review</span></span></button>
            </div>-->
            <div class="buttons-set">
                <button class="button" title="Submit Review" type="submit"><div>SUBMIT REVIEW</div></button>
            </div>
    </form>
    <script type="text/javascript">
    //&lt;![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', 'Please select one of each of the ratings above', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;
    
                    for( var j=0; j &lt; trs.length; j++ ) {
                        var tr = trs[j];
                        if( j &gt; 0 ) {
                            inputs = tr.select('input');
    
                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }
    
                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]&gt;
	
	jQuery('.write_review_heading').click(function() {
		var parent = jQuery(this).parent();
		jQuery('.form-add', parent).show();
	});
    </script>
    </div>
 

            </div>
                
</div>
<script type="text/javascript">
var EasyTabs = Class.create();
EasyTabs.prototype = {
    initialize: function(selector) {
        $$(selector).each(this.initTab.bind(this));
    },

    initTab: function(el) {
        el.href = 'javascript:void(0)';
        if ($(el).up('li').hasClassName('active')) {
            this.showContent(el);
        }
        el.observe('click', this.showContent.bind(this, el));
    },

    showContent: function(a) {
        var li = $(a).up('li'),
            ul = $(li).up('ul');

        ul.select('li'/*, 'ol'*/).each(function(el) {
            var contents = $(el.id + '_contents');
            if (el.id == li.id) {
                el.addClassName('active');
                contents.show();
            } else {
                el.removeClassName('active');
                contents.hide();
            }
        });
    }
}
new EasyTabs('.tabs a');
</script>
               
           </div>