<div id="maincontent"><!--#include virtual="/stormsites/fcuk/includes/top.htm" -->
	<div id="catalogue_thankyou_form" class="tcpl_container clearfix">
		<div class="site_form">
			<h1>Thank You</h1>
			<p>Thanks for signing up to receive our catalogue<br /> We hope you'll enjoy looking at our latest collections.</p>
		</div>
		<div class="need_help_container">
			<h2>Need Help?</h2>
			<p><a href="/content/help/delivery.htm">View Delivery Options</a><br /> <a href="/content/help/returns.htm">View Returns Options</a></p>
			<p><a href="/contactus/">Contact Us</a></p>
		</div>
		<a class="btnLink btnLink_clicktoshop" href="/">Click To Shop</a>
	</div>
	<!--#include virtual="/stormsites/fcuk/includes/bottom_start.htm" --> <!--#include virtual="/stormsites/fcuk/includes/bottom_end.htm" -->
</div>
