<div class="rightstore">
      <div class="storeheading">Chennai</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	 
	  <div class="white">
        <div class="storename">
  Express Avenue Mall<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        (Exclusive Brand Store) </div>
        <div class="storeAddress">Upper Ground Floor <br>
          Express Avenue No.2
          <br>
          Club House Road<br>
          Mount Road<br>
          Chennai - 600002</div>
        <div class="storeContact">+91 44 2846 4201</div>
        <div class="clear"></div>
      </div>
      
      <div class="lightgrey">
        <div class="storename">Phoenix Market City Mall<br>
        (Exclusive Brand Store)<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        </div>
        <div class="storeAddress">UG 42<br> 
        						  Phoenix Market City<br>
								  142, Velachery Main Road<br>
								  Chennai-600042</div>
        <div class="storeContact">+91 44 3008 3393
</div>
        <div class="clear"></div>
        </div>
      
      <div class="white">
        <div class="storename">Shoppers Stop<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        </div>
        <div class="storeAddress">Shoppers Stop<br> 
                                  Ramee Mall<br>
                                  No. 365, Teynampet<br>
                               