<div class="rightstore">
      <div class="storeheading">Coimbatore</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
        <div class="storename"> Shoppers Stop<!--<span class="astric">*</span>--><br></div>
        <div class="storeAddress">Shoppers Stop<br>
        E-City Mall<br>
        S-7 No 474<br>
        Near Rangavilas Mill<br>
		Avinashi Road<br>
        Near PSG Krishnamal College<br>
		Coimbatore - 641004

</div>

        <div class="storeContact">+91 422 4666700</div>
        <div class="clear"></div>
      </div>
      
      	 
      
      	<!--<div class="lightgrey">
        <div class="storename"> Phoenix Market City <span class="astric">*</span>(Exclusive Brand Store)</div>
        <div class="storeAddress">Phoenix Market City <br />
        UG-071, Upper Ground floor<br /> 
        Phoenix Market