<div class="rightstore">
      <div class="storeheading">Dehradun</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
      <div class="white">
        <div class="storename">Rajpur Road<br>(Exclusive Brand Store)</div>
        <div class="storeAddress">208/367<br>
                             Rajpur Road<br>
                          Dehradun - 248001

</div>
 
        <div class="storeContact">+91 135 2711 670</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
      
      <div class="lightgrey">
        <div class="storename">Stanmax</div>
        <div class="storeAddress">125/216<br>
        Main Rajpur Road<br>
		Dehradun- 248001<br>
		Uttarakhand

</div>
 
        <div class="storeContact">+91 135 2740 258 

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>