<div class="rightstore">
      <div class="storeheading">Delhi &amp; NCR </div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
       <div class="white">
        <div class="storename">Select Citywalk <!--<span class="astric">*</span> <span class="astric-grey">*</span> --> <br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">Select Citywalk Mall  <br>
  		G-9 Centre Atrium<br>
      	Ground Floor<br>
      	A 3 District Centre, Saket<br>
      	New Delhi - 110017</div>
        <div class="storeContact">
		+91 11 4059 7575
		</div>
        <div class="clear"></div>
      </div>
      
	  <div class="lightgrey">
        <div class="storename">
  Ambience Mall<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">Ambience Mall 
          <br>
          Shop No G 68<br>
N.H.8 Highway, Near Toll Plaza<br> 
Ambience Island, Gurgaon<br> 
Haryana - 122001</div>
        <div class="storeContact">+91 124 466 5420

		
		</div>
        <div class="clear"></div>
      </div>
      
   	  <div class="white">
        <div class="storename">
  Ambience Mall<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">UG08, Upper Ground Floor <br>
                                  Ambience Mall<br>
                                  Vasant Kunj<br>
                                  New Delhi - 110070<br> 
 </div>
        <div class="storeContact">+91 11 4087 0068
         
         </div>
        <div class="clear"></div>
      </div>   
      
      
      <div class="lightgrey">
        <div class="storename">
  Pacific Mall<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">Shop No. G-014 <br>
                                  Community Centre<br>
                                  Rajouri<br>
                                  New Delhi - 110027<br> 
 </div>
        <div class="storeContact">+91 11 4578 4497
         
         </div>
        <div class="clear"></div>
      </div>   
      
      
      
	  <div class="white">
        <div class="storename">
 DLF Promenade<!--<span class="astric"> *</span> <span class="astric-grey">*</span>--><br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">DLF Promenade<br>
DLF No.108<br> 
          Vasant Kunj<br> 
        New Delhi - 110070</div>
        <div class="storeContact">+91 11 4607 5603</div>
        <div class="clear"></div>
      </div>
	  
	  
	  <div class="lightgrey">
        <div class="storename">
 Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br>
    Eros mall<br>
      Shivaji Palace<br> 
      Near Vishal Cinema<br> 
    Rajouri Garden<br>
    New Delhi - 110027</div>
        <div class="storeContact">+91 93170 08206</div>
        <div class="clear"></div>
      </div>
      
      	  <div class="white">
        <div class="storename">Kapsons<!--<span class="astric">*</span> <span class="astric-grey">*</span> --> <br>
       </div>
        <div class="storeAddress">Moments Mall<br>
  Plot no. 67<br>
     Kirti Nagar<br>
      New Delhi - 110015</div>
        <div class="storeContact">
		
		</div>
        <div class="clear"></div>
      </div>
      
        <div class="lightgrey">
        <div class="storename">Stanmax<!--<span class="astric">*</span> <span class="astric-grey">*</span> --> <br>
       </div>
        <div class="storeAddress">Stanmax<br>
       H-4/2<br>
       Model Town - II<br>
       Delhi -110009</div>
        <div class="storeContact">
		
		</div>
        <div class="clear"></div>
      </div>
	  
       <div class="white">
        <div class="storename">Big Life Rohini<!--<span class="astric">*</span> <span class="astric-grey">*</span> --> <br>
       </div>
        <div class="storeAddress">Vikas Surya Shopping Mall<br>
       Near M2K<br>
       Plot no - 18<br>
       Sector - 3<br>
       Rohini<br>
       New Delhi - 110085 </div>
        <div class="storeContact">
		+91 96508 00966
		</div>
        <div class="clear"></div>
      </div>
      
       <div class="lightgrey">
        <div class="storename">Mall TVR<!--<span class="astric">*</span> <span class="astric-grey">*</span> --> <br>
       </div>
        <div class="storeAddress">Mall TVR<br>
        B-1/32, Ashok Vihar<br>
        Phase 2<br>
        New Delhi - 110052</div>
        <div class="storeContact">
		+91 11 27444972
		</div>
        <div class="clear"></div>
      </div>
	  
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>