<div class="rightstore">
      <div class="storeheading">Dimapur</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Medikhru Complex<br></div>
        <div class="storeAddress">Medikhru Complex<br>
                              	  Near Vijaya Bank<br>
                                  Nyamo Lotha Road<br> 
                        		  Dimapur - 797112 

</div>
 
        <div class="storeContact">+91 3862 224 980</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>