<div class="rightstore">
      <div class="storeheading">Hyderabad</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <div class="white">
        <div class="storename">
		GVK One Mall<br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">GVK One Mall<br>
        						  First Floor<br>
								  Road No-1<br>
								  Banjara Hills<br>
								  Hyderabad - 500034
        </div>
        <div class="storeContact">+91 40 6746 1127</div>
        <div class="clear"></div>
      </div>
      
	  
	  <div class="lightgrey">
        <div class="storename">
 
 Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br>  
         GVK One Mall<br>
         Plot no-6-3-251<br>
         Road No-1<br>
	     Banjara hills<br>
	     Hyderabad - 500034
        </div>
        <div class="storeContact">+91 93239 01286</div>
        <div class="clear"></div>
        </div>
        
        <div class="white">
        <div class="storename">Virata</div>
        <div class="storeAddress">French Connection<br>
Virata Retail Pvt. Ltd <br>
# 128,129<br>
Tyagarayanagar<br>
Kothapet<br>
Hyderabad
        </div>
        <div class="storeContact">+91 40 2404 4566</div>
        <div class="clear"></div>
      </div>
	  
	  
	  <div class="lightgrey">
        <div class="storename">
 
		Airport</div>
        <div class="storeAddress">Shoppers Stop<br>  
		RGI Airport<br>  
		Shamshabad<br>  
		Hyderabad - 501 218.<br>  
		   </div>
        <div class="storeContact">+91 40 6660 3758</div>
        <div class="clear"></div>
        </div>
		<div class="white">
        <div class="storename">	   
			Central</div>
		<div class="storeAddress">Hyderabad Central<br>  
			G.S. Mall 674/1 <br>
			Punjagutta Cross Road <br>
			Opp: Punjagutta Police Station <br>
			Hyderabad - 500 082.<br> </div>
			<div class="storeContact">+91 40 6643 0000</div>
        <div class="clear"></div>
        </div>
	  
	  <div class="lightgrey">
        <div class="storename">
 
		Jade Blue</div>
        <div class="storeAddress">Jade Blue Lifestyle India Ltd.<br>  
		Park Citi Plaza<br>  
		Road No.1<br>  
		Banjara Hills<br>
		Hyderabad - 500 034.<br> 		
		
        </div>
        <div class="storeContact">+91 40 2330 7774</div>
        <div class="clear"></div>
        </div>
	 
	  
	 
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>