<div class="rightstore">
      <div class="storeheading">Lucknow</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
        <div class="storename"> Shoppers Stop <!--<span class="astric">*</span>--></div>
        <div class="storeAddress">Shoppers Stop <br>
        Fun Republic Mall<br> 
        Besides Eldeco<br>
        Opposite Paryatan Bhavan<br>
        Gomti Nagar<br>
        Lucknow - 226010</div>
        <div class="storeContact"></div>
        <div class="clear"></div>
        </div>
        
        <div class="lightgrey">
        <div class="storename"> Kohli Brothers  <!--<span class="astric">*</span>--></div>
        <div class="storeAddress">French Connection<br>
Kohli Brothers<br>
50, Hazratganj<br>
Lucknow - 226001<br>
</div>
        <div class="storeContact">+91 522 329 8551</div>
        <div class="clear"></div>
        </div>
        
        <div class="white">
        <div class="storename">Wardrobe<!--<span class="astric">*</span>--></div>
        <div class="storeAddress">French Connection<br>
Toggery The Fashion<br>
1/243<br>
Vikram Khan<br>
Near  Pritampuram<br>
Gomti Nagar<br>
Lucknow - 226010
</div>
        <div class="storeContact">+91 522 261 3132</div>
        <div class="clear"></div>
      </div>
      
      <!--	<div class="lightgrey">
        <div class="storename"> Phoenix Market City <!--<span class="astric">*</span>(Exclusive Brand Store)</div>
        <div class="storeAddress">Phoenix Market City <br />
        UG-071, Upper Ground floor<br /> 
        Phoenix Market City Mall<br />
        Near Hyatt Hotel<br />
        Viman Nagar<br />
        Pune - 411014</div>
        <div class="storeContact">+91 20 30950228</div>
        <div class="clear"></div>
      </div>-->
	  
      
      
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>