<div class="rightstore">
      <div class="storeheading">Nellore</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
 <div class="white">
        <div class="storename">Modern Era
        <br>
        </div>
        <div class="storeAddress">French Connection<br>
Modern Era<br>
23-4-76 Kings Court Avenue<br>
Magunta Layout<br>
Nellore  - 524003
</div>
 
        <div class="storeContact">+91 99160 81705

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>