<div class="rightstore">
      <div class="storeheading">Panchkula</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Sector 8<br>(Exclusive Brand Store)</div>
        <div class="storeAddress">DSF 401<br>
        						  Sector - 8<br>
								  Next to Petrol Pump<br>
								  Panchkula - 134 109 

</div>
 
        <div class="storeContact">+91 85588 12037</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>