<div class="rightstore">
      <div class="storeheading">Panipat</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">Suvidha Store<br></div>
        <div class="storeAddress">Suvidha Store<br>
								  Gohana Chowk<br>
								  GT Road<br>
								  Panipat<br>
								  Haryana - 132103 

</div>
 
        <div class="storeContact">+91 180 4023 111</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-