<div class="rightstore">
      <div class="storeheading">Patiala</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <div class="white">
        <div class="storename">
			   Kapsons Fashion</div>
        <div class="storeAddress">Kapsons Fashion<br>
        						  SCO 7-8<br>
								Bhupindra Road<br>
								Patiala- 147001  <br>
								        </div>
        <div class="storeContact"></div>
        <div class="clear"></div>
      </div>
      
  
	  









 
	 
	  
	 
	  
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>