<div class="rightstore">
      <div class="storeheading">Raipur</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
	  <!-- <div class="white">
        <div class="storename"> Jewel Square<!--<span class="astric"> *</span> <span class="astric-grey">*</span><br />
(Exclusive Brand Store) </span></div>
        <div class="storeAddress">LG-3,Jewel Square<br />
                                  Ground Floor<br />
                                  Adjacent to Taj Blue Diamond<br />
                                  Koregaon Park<br />
                                  Pune - 411 001.</div>
        <div class="storeContact">+91 20 4128 5555 </div>
        <div class="clear"></div>
      </div> -->
	  
	  
	  <div class="white">
        <div class="storename"> Magneto Mall <!--<span class="astric">*</span>--><br>(Exclusive Brand Store) </div>
        <div class="storeAddress">Magneto Mall <br>
        Shop No 34<br>
		Ground Floor<br>
		GE Road<br>
		Labhandi<br>
		Raipur 492001</div>

        <div class="storeContact">+91 771 3009 190</div>
        <div class="clear"></div>
      </div>
      
      	  <div class="lightgrey">
        <div class="storename"> Fashion House <!--<span class="astric">*</span>--></div>
        <div class="storeAddress">Fashion House<br>
        						  Municipal House No. 34<br>
							   	  Plot no. 5/3<br>
						 		  Beside Simran Tower<br>
								  Opp. LIC building<br>
								  Pandri<br>
								  Raipur- 420009</div>

        <div class="storeContact">+91 771 4095 294</div>
        <div class="clear"></div>
      </div>
      
      	<!--<div class="lightgrey">
        <div class="storename"> Phoenix Market City <span class="astric">*</span>(Exclusive Brand Store)</div>
        <div class="storeAddress">Phoenix Market City <br />
        UG-071, Upper Ground floor<br /> 
        Phoenix Market City Mall<br />
        Near Hyatt Hotel<br />
        Viman Nagar<br />
        Pune - 411014</div>
        <div class="storeContact">+91 20 30950228</div>
        <div class="clear"></div>
      </div>-->
	  
      
      
	  <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>