<div class="rightstore">
      <div class="storeheading">Rajkot</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
        
      </div><div class="white">
        <div class="storename">Options <br></div>
        <div class="storeAddress">Options<br>
								  Opposite Jilla Panchayat<br>
								  Dr. Yagnik Road<br>
								  Rajkot - 3600001<br>
								  Gujarat
</div>
 
        <div class="storeContact">+91 281 2450 845

</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>