<style>
.col-main{	margin-left:-40px;}
.col-main img{	margin-left:-237px;}
.leftmenu a{
	text-decoration:none;
	color:#4A4A4A;
	font-weight:bold;
	
	}
.breadcrumbs 
{
display:none;	
}


.main_content_image 
{
	right:0 !important;
}
.leftmenu
{
 float: left;
    font-size: 11px;
    font-weight: bold;
    padding-left: 10px;
    text-align: left;
    width: 155px;
	margin-left:-241px;
}
.rightstore {
margin-top:30px;
    float: right;
    font-size: 11px;
    margin-right: 20px;
    text-align: left;
    width: 750px;
}
.storetitle {
    background-color: #DCDCDC;
    font-weight: bold;
    height: 12px;
    padding: 10px;
}
.storeheading {
    border-bottom: 1px solid #4A4A4A;
    font-size: 12px;
    font-weight: bold;
}
.white {
    background-color: #FFFFFF;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.lightgrey {
    color: #4A4A4A;
}
.lightgrey {
    background-color: #F4F4F4;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.storename {
    float: left;
    font-size: 12px;
    font-weight: bold;
    margin-right: 20px;
    width: 150px;
}
.storeAddress {
    float: left;
    font-size: 12px;
    margin-right: 20px;
    width: 330px;
}
.storeContact {
    float: left;
    font-size: 12px;
    width: 110px;
}	
</style>
<div class="leftmenu">
      	<p style="padding-top:14px;"></p>	
      	<p class="sl-left-menu-pad"><a href="#">Agra</a></p>
        <p class="sl-left-menu-pad"><a href="#">Ahmedabad</a></p>
        <p class="sl-left-menu-pad"><a href="#">Amritsar</a></p>
        <p class="sl-left-menu-pad"><a href="#">Bangalore</a></p>
        <p class="sl-left-menu-pad"><a href="#">Bhopal</a></p>
        <p class="sl-left-menu-pad"><a href="#">Bhubaneswar</a></p>
        <p class="sl-left-menu-pad"><a href="#">Bilaspur</a></p>
        <p class="sl-left-menu-pad"><a href="#">Chandigarh</a></p>	
        <p class="sl-left-menu-pad"><a href="#">Chennai</a></p>
        <p class="sl-left-menu-pad"><a href="#">Coimbatore</a></p>
        <p class="sl-left-menu-pad"><a href="#">Dehradun</a></p>
        <p class="sl-left-menu-pad"><a href="#">Delhi &amp; NCR</a></p>
        <p class="sl-left-menu-pad"><a href="#">Dimapur</a></p>
         <p class="sl-left-menu-pad"><a href="#">Gandhidham</a></p>
        <p class="sl-left-menu-pad"><a href="#">Goa</a></p>
        <p class="sl-left-menu-pad"><a href="#">Guwahati</a></p>
        <p class="sl-left-menu-pad"><a href="#">Hyderabad</a></p>
        <p class="sl-left-menu-pad"><a href="#">Indore</a></p>
        <p class="sl-left-menu-pad"><a href="#">Jalandhar</a></p>
        <p class="sl-left-menu-pad"><a href="#">Jammu</a></p>
        <p class="sl-left-menu-pad"><a href="#">Kanpur</a></p>
        <p class="sl-left-menu-pad"><a href="#">Karnal</a></p>
		<p class="sl-left-menu-pad"><a href="#">Kochi</a></p>
		<p class="sl-left-menu-pad"><a href="#">Kolkata</a></p>
        <p class="sl-left-menu-pad"><a href="#">Lucknow</a></p>
        <p class="sl-left-menu-pad"><a href="#">Ludhiana</a></p>
	  	<p class="sl-left-menu-pad select">Mumbai</p>
        <p class="sl-left-menu-pad"><a href="#">Nellore</a></p>
      	<p class="sl-left-menu-pad"><a href="#">Panchkula</a></p>
        <p class="sl-left-menu-pad"><a href="#">Panipat</a></p>
        <p class="sl-left-menu-pad"><a href="#">Pune</a></p>
        <p class="sl-left-menu-pad"><a href="#">Puri</a></p>
        <p class="sl-left-menu-pad"><a href="#">Raipur</a></p>
        <p class="sl-left-menu-pad"><a href="#">Rajkot</a></p>
        <p class="sl-left-menu-pad"><a href="#">Surat</a></p>
        <p class="sl-left-menu-pad"><a href="#">Vadodra</a></p>
        <p class="sl-left-menu-pad"><a href="#">Varanasi</a></p>
        <p class="sl-left-menu-pad"><a href="#">Vijaywada</a></p>
    </div>
    