<div class="rightstore">
      <div class="storeheading">Vadodra</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div><div class="white">
        <div class="storename">The Hub<br></div>
        <div class="storeAddress">The Hub<br>
								  Spenta<br>
								  Opp Pizza Hut<br>
								  Race Course Circle<br>
								  Vadodara - 390007 

</div>
 
        <div class="storeContact">+91 265 2314 677</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    