<div class="rightstore">
      <div class="storeheading">Vijaywada</div>
      <div class="storetitle">
        <div class="storename">Store</div>
        <div class="storeAddress">Address</div>
        <div class="storeContact">Phone</div>
      </div>
      
 <div class="white">
        <div class="storename">Kala Niketan
        <br>
        </div>
        <div class="storeAddress">French Connection<br>
Kalanikethan Silks Pvt Ltd<br>
MG Road<br>
Opposite Chennupati Petrol Pump<br>
Vijayawada ? 520010
 </div>
 
        <div class="storeContact">+91 866 248 8333</div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
	  <!--<div><span class="astric">* </span>Fragrance available &nbsp;|  <span class="astric-grey">*</span> Sunglasses available</div>-->
    </div>