<div id = "content">
<p class="banner_img"><img src="<?php echo $this->getBaseUrl();?>media/storelocator.jpg" /></p>
	<div class = "left_filters">
		<?php $cities = $this->getAllCities(); ?>
		<div class = "city">
			<ul  id="city">
		<?php 	$configValue = Mage::getStoreConfig('store/storeinfo/storecities');		?>
					<?php foreach($cities as $country => $sagrigated_cities){?>
						<?php if(strpos($country, 'Opening Soon') === false){?>
							<li class="country_name" id="<?php echo str_replace(" ","_",$country);?>"style="margin-bottom: 5px;"><?php echo $country;?></li>
						<?php }else{ ?>
							<li class="city_name opening_soon <?php echo str_replace("Opening_Soon_in_","",str_replace(" ","_",$country));?>" style="margin-bottom: 12px;"><?php echo $country;?></li>
						<?php } ?>
					<?php foreach($sagrigated_cities as $city) { ?>
							<?php  if(strtolower($city)==$configValue){?>
							<li class="city_name active <?php if(strpos($country, 'Opening Soon') === false){echo str_replace(" ","_",$country); } else{echo str_replace("Opening Soon_in_","",str_replace(" ","_",$country)); } ?>"><?php echo $city; ?></li>
							<?php }else{?>
							<li class="city_name <?php if(strpos($country, 'Opening Soon') === false){echo str_replace(" ","_",$country); } else{echo str_replace("Opening_Soon_in_","",str_replace(" ","_",$country)); } ?>"><?php echo $city; ?></li>
							<?php } ?>
					<?php } ?>
				<?php } ?>
			</ul>
		</div>
	</div>
	<?php
		 $resource = Mage::getSingleton('core/resource');
		 $readConnection = $resource->getConnection('core_read');
		 $query = "SELECT * FROM storelocator where city='$configValue'";
		 $results = $readConnection->fetchAll($query);
	?>
	<?php ?>
	<div class="address_wrapper">
		<div class="storeheading"><?php echo ucwords(strtolower($configValue))?></div>
		<div class="storetitle">
			<div class="storename">Store</div>
			<div class="storeAddress">Address</div>
			<div class="storeContact">Phone</div>
		</div>
		<div class="addressbox">
			<?php $exclusive = $this->exclusiveStore($configValue);
					$inclusive = $this->inclusiveStore($configValue);
				echo $exclusive.$inclusive;
			?>
		</div>
	</div>
</div>
<script type="text/javascript">

jQuery("document").ready(function($)
{	//$('li').addClass('active');
	$("#city .city_name").click(function()
		{
			$('li').removeClass('active');
			$(this).addClass('active');
			var city=$(this).text();
			$('.storeheading').html(city);
			var city_url = "<?php echo $this->getBaseUrl().'storelocator/index/city'?>";
			var pathname = window.location;
			if(pathname == "http://frenchconnection.in/storelocator")
			{
				city_url = "http://frenchconnection.in/storelocator/index/city"
			}
			//alert(city);
			$.post(
				city_url,
				{city:city},
				function(data){
					$(".addressbox").html(data);
				}
			);

		});

});
</script>
<style type="text/css">
#content .left_filters
{float: left;
font-size: 11px;
font-weight: bold;
padding-left: 10px;
text-align: left;
width: 155px;
padding-top:10px !important;}

.city .city_name{margin: 0 0 1em;text-decoration: none;color: #4A4A4A;font-weight: normal; text-transform: capitalize; display: none;}
.city .city_name:hover{
text-decoration: none;
color: #4A4A4A;
font-weight: bold;
}
.storeheading{color: #4A4A4A;text-transform: capitalize;}
.address_wrapper{float:right;}
.storename
{
float: left;
width: 200px;
padding-left: 15px;
padding-right: 40px;
color: #4A4A4A;
}
.storeAddress
{
float: left;
width: 265px;
padding-right: 100px;
color: #4A4A4A;
}
.storeContact{float:left;width: 125px;color: #4A4A4A;}
.banner_img{margin-bottom: 20px;}
.addressbox{overflow: hidden;}
.add_wrapper{
overflow: hidden;
padding-bottom: 10px;
padding-top: 10px;
}
 .add_wrapper:nth-child(odd){background-color:#F4F4F4}
.storelocator-index-index .left_filters #city .city_name{cursor:pointer;}
.storelocator-index-index .active{font-weight: bold;}
.storelocator-index-index .opening_soon { color: #000; font-weight: bold;}
.storelocator-index-index .country_name { font-size: 14px; background-color: #DCDCDC; padding: 5px; cursor: pointer;}
.storelocator-index-index ul#city { margin-top: 40px;}
</style>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('.country_name').click(function(){
			var country = $(this).attr('id');
			$('.city_name').stop().slideUp('slow')
			$('.'+country).stop().slideDown('slow');
		});
		$('.country_name').first().trigger('click');
	});
</script>
