<object classid="clsid:classid" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="940" height="369">
<param name='movie' value="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/images/lookbook/men_lookbook.swf'?>">
<param name='quality' value='high'>
<param name="wmode" value="transparent">
<embed class="look_book_flash" src="<?php echo $this->getBaseUrl().'skin/frontend/fcuk/default/images/lookbook/men_lookbook.swf';?>"
 quality='high' wmode="transparent" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="940" height="600">
</embed>
</object> 
