<style>

.leftmenu a{
	text-decoration:none;
	color:#4A4A4A;
	font-weight:normal;
	
	}
	.leftmenu a:visited,.leftmenu a:hover{
	text-decoration:none;
	color:#4A4A4A;
	font-weight:bold;
	
	}
.breadcrumbs 
{
display:none;	
}


.main_content_image 
{
	right:0 !important;
}
.leftmenu
{
 float: left;
    font-size: 11px;
    font-weight: normal;
    padding-left: 10px;
    text-align: left;
    width: 155px;
	
}
.rightstore {
margin-top:30px;
    float: right;
    font-size: 11px;
    margin-right: 20px;
    text-align: left;
    width: 750px;
}
.storetitle {
    background-color: #DCDCDC;
    font-weight: bold;
    height: 12px;
    padding: 10px;
}
.storeheading {
    border-bottom: 1px solid #4A4A4A;
    font-size: 12px;
    font-weight: bold;color: #4A4A4A;
}
.white {
    background-color: #FFFFFF;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.lightgrey {
    color: #4A4A4A;
}
.lightgrey {
    background-color: #F4F4F4;
    border-top: 1px solid #FFFFFF;
    padding: 10px;
}
.storename {
    float: left;
    font-size: 12px;
    font-weight: bold;
    margin-right: 20px;
    width: 150px;color: #4A4A4A;
}
.white .storename,.lightgrey .storename{
    float: left;
    font-size: 12px;
    font-weight:normal ;
    margin-right: 20px;
    width: 150px;
	color: #4A4A4A;
}

.storeAddress {
    float: left;
    font-size: 12px;
    margin-right: 20px;
    width: 330px;
	color: #4A4A4A;
	
}
.storeContact {
    float: left;
    font-size: 12px;
    width: 110px;
	color: #4A4A4A;
}	
</style>


<div class="leftmenu">
      	<p style="padding-top:14px;"></p>	
      	<p class="sl-left-menu-pad"><a href="/stores_agra">Agra</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_ahmedabad">Ahmedabad</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_amritsar">Amritsar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bangalore">Bangalore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bhopal">Bhopal</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bhubaneswar">Bhubaneswar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_bilaspur">Bilaspur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_chandigarh">Chandigarh</a></p>	
        <p class="sl-left-menu-pad"><a href="/stores_chennai">Chennai</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_coimbatore">Coimbatore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_dehradun">Dehradun</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_delhi">Delhi &amp; NCR</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_dimapur">Dimapur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_goa">Goa</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_guwahati">Guwahati</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_hyderabad">Hyderabad</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_indore">Indore</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_jaipur">Jaipur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_jalandhar">Jalandhar</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_jammu">Jammu</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_kanpur">Kanpur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_karnal">Karnal</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_kochi">Kochi</a></p>
		<p class="sl-left-menu-pad"><a href="/stores_kolkata">Kolkata</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_lucknow">Lucknow</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_ludhiana">Ludhiana</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_mumbai">Mumbai</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_nellore">Nellore</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_panchkula">Panchkula</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_panipat">Panipat</a></p>
		        <p class="sl-left-menu-pad"><a href="/stores_patiala">Patiala</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_pune">Pune</a></p>

		<p class="sl-left-menu-pad"><a href="/stores_puri">Puri</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_raipur">Raipur</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_rajkot">Rajkot</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_surat">Surat</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_vadodra">Vadodra</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_varanasi">Varanasi</a></p>
        <p class="sl-left-menu-pad"><a href="/stores_vijaywada">Vijaywada</a></p>
      	<p class="sl-left-menu-pad select"><a href="/Openingsoon">Opening Soon</p>
	  	<p><a class="thickbox" title="" href="storegallery_fcuk.html?keepThis=true&amp;TB_iframe=true&amp;height=415&amp;width=600"><span class="gallery">View Our Store Gallery</span></a></p>
      <p><a href="view_map"><span class="gallery">View Map</span></a></p>
    </div>    
<div class="rightstore">
      <div class="storeheading">Mumbai</div>
      <div class="storetitle">
        <div class="storename storename_header">Store</div>
        <div class="storeAddress storeAddress_header">Address</div>
        <div class="storeContact storeContact_header">Phone</div>
      </div>
      
            <div class="white">
             <div class="storename">Linking Road <!--<span class="astric"> *</span> <span class="astric-grey">*</span>--> <br>
        	(Exclusive Brand Store)</div>
        	<div class="storeAddress">
			317, Rinku Appartment<br>
			Ground Floor<br>
			Khar Linking Road<br>
			Mumbai - 400052</div>
 		<div class="storeContact">+91 22 2648 2143</div>
        <div class="clear"></div>
      </div>
      
      
      <div class="lightgrey">
      <div class="storename">
		Phoenix Marketcity Mall <!--<span class="astric"> *</span> <span class="astric-grey">*</span>--> <br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">
			French Connection<br>
			UG-23A, Upper Ground Floor<br>
			L.B. S. Marg<br>   
			Kurla (West)<br>
			Mumbai 400 070.</div>
 		<div class="storeContact">+91 22 6180 1216</div>
        <div class="clear"></div>
      </div>
      
      
 <div class="white">
        <div class="storename">Infiniti Mall <!--<span class="astric"> *</span> <span class="astric-grey">*</span>--> <br>
		(Exclusive Brand Store)</div>
        <div class="storeAddress">
			French Connection<br>
			GF017, Upper Ground Floor<br>
			Podium Level, Infinity Mall<br>
			Link Road, Malad West<br>
			Mumbai-400 064</div>
        <div class="storeContact">+91 22 2889 3300 </div>
        <div class="clear"></div>
      </div>   
      
      
        <div class="lightgrey">
        <div class="storename">
 			Palladium Mall <!--<span class="astric">*</span> <span class="astric-grey">*</span>-->  <br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">Palladium Mall <br>
			Phoenix Mills Compound<br>
 			462, Senapati Bapat Marg<br>
 			Lower Parel<br>
 			Mumbai - 400013</div>
        <div class="storeContact">+91 22 3072 8800 </div>
        <div class="clear"></div>
        </div>
        
        <div class="white">
        <div class="storename">
 			R-City Mall <!--<span class="astric">*</span> <span class="astric-grey">*</span>-->  <br>
        (Exclusive Brand Store)</div>
        <div class="storeAddress">Phase 2, Ground Floor <br>
			Ghatkopar (W)<br>
 			Mumbai - 400086</div>
        <div class="storeContact">+91 22 6643 0919 </div>
        <div class="clear"></div>
        </div>
      
      <div class="lightgrey">
        <div class="storename">Vama <!--<span class="astric">*</span>--> </div>
        <div class="storeAddress">Vama <br>
   			Kanchanjunga<br> 
  			Peddar Road<br>
  			Cumbala Hill<br> 
  			Mumbai - 400026</div>
        <div class="storeContact">+91 22 6512 0518 </div>
        <div class="clear"></div>
        </div>
      
	    <div class="white">
        <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br> 
        Dynamix Mall<br>
        Sant Dhyaneshwar Marg<br>
        JVPD Scheme<br>
        Next to Chandan Cinema Hall<br>
        Juhu<br>
        Mumbai - 400049</div>
        <div class="storeContact">+91 93239 14920</div>
        <div class="clear"></div>
        </div>
      
	    <div class="lightgrey">
        <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br> 
        In Orbit Mall<br> 
        Plot No 1406-A<br>
        28/A Link Road<br>
        Malad (W)<br> 
        Mumbai - 400064</div>
        <div class="storeContact">+91 93239 14932</div>
        <div class="clear"></div>
      </div>
      
	  <div class="white">
      <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br>
        Linking Road<br>
        Bandra (W)<br>
        Mumbai - 400049</div>
        <div class="storeContact">+91 93239 14929</div>
        <div class="clear"></div>
      </div>
      
      <div class="lightgrey">
      <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br>
        R-City Mall<br>
        2nd Floor<br>
        Ghatkopar- 400086</div>
        <div class="storeContact">+91 97730 87195</div>
        <div class="clear"></div>
      </div>
      <div class="white">
        <div class="storename">Shoppers Stop</div>
        <div class="storeAddress">Shoppers Stop<br>
        Inorbit Mall<br>
        Ground Floor<br>
        Unit No:G - A2 &amp; F - A2<br>
        Plot No 39/1<br>
        Vashi - 400705 </div>
        <div class="storeContact"></div>
        <div class="clear"></div>
      </div>
      
        </div>    