<?php   $idval=$this->getRequest()->getParam('id'); 
    	 $countryidnew=$this->getRequest()->getParam('country_id'); 
	//$idval=100;
			if($idval)
			{
			$resource = Mage::getSingleton('core/resource');
			$read = $resource->getConnection('core_read');
			$query1 = "SELECT * FROM findaddress where id=$idval limit 0,1";
			$result1=$read->query($query1);
			$postcodeadd = $result1->fetchAll();

			
			}
			//print_r($postcodeadd);
?>
<div class="billing_address_content" >

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getBaseUrl().'requestcatalog/index/store' ?>" method="get" id="form-validate" name="form-validate">
   
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
      <article class="site_form tcpl_page">
        <header>
            <h1>Request a catalogue</h1>
        </header>

        <p>
            Please check and confirm your catalogue delivery address.<br>
            Fields marked with an * are mandatory and must be completed.
        </p><br/>
        <ul class="form-list" >
           <div class="addressDiv">
                <?php echo $this->getNameBlockHtml() ?>
			</div>	
				
			 <div class="addressDiv">
                <div class="addressName"><?php echo $this->__('Title') ?></div>
                <div class="addressinputArea">
                 <select class="selectinput" id="title" name="title">
					<option value="Mr">Mr</option>
					<option value="Mrs">Mrs</option>
					<option value="Miss">Miss</option>
					<option value="Ms">Ms</option>
					<option value="Dr">Dr</option>

				</select>
                </div>
			</div>
			 <div class="addressDiv">
                <div class="addressName"><?php echo $this->__('First Name') ?></div>
                <div class="addressinputArea">
                    <input type="text" name="firstname" id="firstname" title="<?php echo $this->__('First Name') ?>" value="" class="input-text required-entry" />
                </div>
			</div>	
			<div class="addressDiv">
                <div class="addressName"><?php echo $this->__('Last Name') ?></div>
                <div class="addressinputArea">
                    <input type="text" name="lastname" id="lastname" title="<?php echo $this->__('Last Name') ?>" value="" class="input-text required-entry" />
                </div>
			</div>	
			<div class="addressDiv">
                <div class="addressName"><?php echo $this->__('Email') ?></div>
                <div class="addressinputArea">
                    <input type="text" name="email" id="email" title="<?php echo $this->__('Email') ?>" value="" class="input-text required-entry" />
                </div>
			</div>
            
        <ul class="form-list">
		    <div class="addressForm">
	
           
            <div class="addressDiv">
                <div class="addressName"><?php echo $this->__('Address') ?><em>*</em></div>
                <div class="addressinputArea">
                    <input type="text" name="address" value="<?php echo $postcodeadd[0]['street']; ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="inputSty input-text <?php echo $_streetValidationClass ?>" />
                </div>
				<!--div class="addressinputArea">
                    <input type="text" name="address" value="<?php //echo $postcodeadd[0]['street']; ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="inputSty input-text <?php echo $_streetValidationClass ?>" />
                </div-->
            </div>
          
               <div class="addressDiv">
                    <div class="addressName"><?php echo $this->__('Town or City ') ?><sup>*</sup></div>
                    <div class="addressinputArea">
                        <input type="text" name="city" value="<?php echo $postcodeadd[0]['city']; ?>"  title="<?php echo $this->__('City') ?>" class="inputSty input-text" id="city" />
                    </div>
                </div>
              
                   <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('State') ?><sup>*</sup></DIV>
                    <div class="addressinputArea">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                       
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $postcodeadd[0]['state']; ?>"  title="<?php echo $this->__('State/Province') ?>" class="inputSty input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
           
            <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('Postcode') ?><sup>*</sup></div>
                    <div class="addressinputArea">
                        <input type="text" name="postcode" value="<?php echo $postcodeadd[0]['postcode']; ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="inputSty input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="addressDiv">
				<div class="addressName"><?php echo $this->__('Country') ?><sup>*</sup></div>
                    <div class="addressinputArea">
					<?php  $countryselected= $postcodeadd[0]['country_id'];
                    if($countryidnew!=''){
                         $countryselected=$countryidnew;
                    }
					
					
					if($countryselected)
			        {
	
						// $countryselected looks like "US"
						$country = Mage::getModel('directory/country')->loadByCode($countryselected);
						echo $country->getName();

			
					}
			?>
                    </div>
                </div>
				<div>
				<span id="receivedemail"  class="receivedemail">Would you like to receive french connection emails?</span> <input type="checkbox" checked="checked" name="chkReceiveEmails" id="chkReceiveEmails"><br> (we will not give out your email address to others - ever)
				
				</div>
            <div class="addressDiv" id="row_marketing_where">
            <label id="WhereDidYouHearAboutUs" for="WhereDidYouHearAboutUs">where did you hear about us?</label>

            <select class="selectinput" id="WhereDidYouHearAboutUsselect" name="WhereDidYouHearAboutUsselect">
				<option value="">please select...</option>
				<option value="I was sent a catalogue">I was sent a catalogue</option>
				<option value="You sent me an email">You sent me an email</option>
				<option value="MagazineAd">Magazine</option>
				<option value="NewspaperAd">Newspaper</option>
				<option value="Friend">A friend told me</option>
				<option value="A friend told me">I buy online already</option>
				<option value="I have seen your stores">I have seen your stores</option>

			</select>
        </div>
			
        </ul>
  
  
        <div class="addressDiv" style="*margin-bottom:20px;  margin:20px 0">
		<span class="back-link">
		<a href="<?php echo $this->escapeUrl($this->getBaseUrl().'requestcatalog/index/index')?>">
		<span class="goBackBtn"></span>
		</a>
		</span>
		<input type="submit" title="" value="&nbsp;" class="continueBtn" />
   </div>
   
</form>
</div>
<div id="catalogue_address_form">
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
   
//]]>
jQuery('select[name="country_id"]').find('option[value="<?php echo $this->getRequest()->getParam('country_id')?>"]').attr("selected",true);
</script>

	<style>
.billing_address_content {
float: left;
width: 440px;
margin: 0px 5px 10px 10px;
background: #F0EFEF;
padding: 20px;
color: #666666;
font-family: sans-serif;
}
.form-list input.input-text, .form-list select.select-input-text {
width: 190px;;
border: 1px solid #999999;
padding: 3px 5px 3px 5px;
}
#receivedemail{padding-right:30px;}

	#catalogue_address_form {
    background-image: url(<?php echo $this->getSkinUrl('/images/bg_catalogue.jpg') ?>);
    background-position: right top;
    background-repeat: no-repeat;
    height: auto !important;
    margin-top: 2px;
    min-height: 595px;

}
 .tcpl_container {
    margin-left: auto;
    margin-right: auto;
    width: 984px;
}
.clearfix {
    display: block;
}
#catalogue_address_form .site_form {
margin: 0px 0 0px 0;
width: 450px;
padding: 20px;
background: #F0EFEF;
}
article.tcpl_page h1 {
margin: 0 0 20px 0;
padding: 0;
font-weight: bold;
font-size: 2.7em;
color: #363536;
text-transform: uppercase;
line-height: 1;
}

article.tcpl_page{
font-size: 0.95em;
color: #666666;
line-height: 1.4;
font-family: sans-serif;
}
p {
display: block;
-webkit-margin-before: 1em;
-webkit-margin-after: 1em;
-webkit-margin-start: 0px;
-webkit-margin-end: 0px;
}
.site_form label, .site_form .label {
float: left;
width: 90px;
padding: 3px 10px 3px 0px;
}
.site_form .selectinput {
float: left;
width: 202px;
border: 1px solid #999999;
margin: 3px 0px 3px 0px;
}
.site_form .textinput {
float: left;
width: 190px;
border: 1px solid #999999;
padding: 3px 5px 3px 5px;
border-radius: 0px;
} 
	</style>