<nav class="grid_6" id="subNav">
    <ul>
  		<li class="subnav_title">Contact Us</li>
		<li class="subnav_title_divide"></li>
		<li class="subnav_title1">How to Contact Us</li>
		<li class="open">
    		<ul style="display:block; margin: 10px 0 10px 0;">
				<li><a href="#phone" title="Phone">By Phone</a></li>
				<li><a href="#emailaddress" title="Email">By Email</a></li>
				<li><a href="#post" title="Post">By Post</a></li>
				<li><a href="#bytwitter" title="Twitter">By Twitter</a></li>
				<!--  <li><a href="#customercare" title="Customer Care">Customer Care</a></li> -->
				<!-- <li><a href="#online" title="Online Service Issue Contact">Online Service Issue</a></li> -->
			</ul>
  		</li>
	</ul>
</nav>