<div class="block block-subscribe">
     <div class="subscribe_option f-right">
    <form action="" method="post" onsubmit="return check()" id="newsletter-validate-detail" name="newsletter-validate-detail">
        <div class="block-content block-message">
        
            <div class="form-subscribe-header">
            
				<p>Subscribe for Latest Updates and Special Offers </p>
            </div>
          
           <div class="margin_bot">            
                
				<div class="input-box">
					<input name="email" type="text" id="newsletter" class="fc-mail-field validate-email" placeholder="Enter your email address..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
				   <!--input type="text" name="email" value="Enter your email address..." id="newsletter" autocomplete="off" title="<?php echo $this->__('Enter your email address') ?>" class="input-text validate-email" onfocus="javascript: if(this.value=='Enter your email address...'){this.value='';}"/>
				   <span class="email-message" style="color:red"></span-->
					<span class="email-message" style="color:red"></span>
				</div>
			   <div class="actions icons_news">
					<button type="submit" title="<?php //echo $this->__('Subscribe') ?>" id="newsletter-button" class="button"><?php //echo $this->__('Subscribe') ?><img src="<?php echo $this->getSkinUrl('images/sms.jpg')?>"></button>
				</div>
				
            </div>
		<div class="or"></div>
            <div class="margin_bot">            
			   <div class="input-box-sms">
				   <input name="mobileno" type="text"  id="mobileno" class="fc-mail-field validate-number" placeholder="Enter your Mobile Number..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
				   <!--input type="text" name="mobileno" value="Enter your mobile number..." id="mobileno"  autocomplete="off" title="<?php echo $this->__('Enter your mobile number') ?>" class="input-text validate-number" onfocus="javascript: if(this.value=='Enter your mobile number...'){this.value='';}"/>
					  <span class="mobileno-message" style="color:red"></span-->
						 <span class="mobileno-message" style="color:red"></span>
				</div>
               <div class="actions icons_news">
					<button type="submit" title="<?php //echo $this->__('Subscribe') ?>" id="mobileno-button" class="button"><?php //echo $this->__('Subscribe') ?><img src="<?php echo $this->getSkinUrl('images/mobile.jpg')?>"></button>
				</div>
            </div>
            <span class="error-message" style="color:red;float: left;margin-left: 100px;"></span>
        </div>
	
    </form>
		<!--div class="newsletter-msg" style="display:none"><span class="red"></span></div-->
		<div class="success_msg"><div class="newsletter-result-msg" style="color:red">Thank you for subscription</div></div>
    </div>
	</div>
    <script type="text/javascript">
/* 	jQuery('document').ready(function(){jQuery('.success_msg').css('display','none');}); */
	 function check(){
		 
		
		var email = jQuery('.validate-email').val();
		var mobileno = jQuery('.validate-number').val();	
	//	alert(email);
		
		if(email=='' && mobileno=='')
		{
		//	alert('please enter values');
				jQuery('.error-message').html('Please Fill Atleast One Field');
				 jQuery('.error-message').delay(4000).fadeOut();
				 
				 return false;
				 
		
		}
		else
		{
			if(email!='' && mobileno=='')
		
			{

						var atpos=email.indexOf("@");
						var dotpos=email.lastIndexOf(".");
						if (atpos<1 || dotpos<atpos+2 || dotpos+2>=email.length)
						{
							jQuery('.email-message').html('Please Enter Valid Email address');
							jQuery('.email-message').delay(8000).fadeOut();
							
							//alert("Not a valid e-mail address");
							return false;
						}
						else
						{
						var link= '<?php echo $this->getBaseUrl().'subscription/index/store'; ?>';
							 jQuery.ajax({
								 type: "POST",
								 url: link,
								 data: {email:email,mobileno:mobileno},
								 success: function(msg)
								 {
								 
								  jQuery('.block-message').delay(300).fadeOut();	
								 jQuery('.success_msg').delay(1000).fadeIn();
								jQuery('.block-message').delay(8000).fadeIn(function(){jQuery('#newsletter').val('');});								
								jQuery('.success_msg').delay(7000).fadeOut();	
								
										
								 }
				
							});
						return false;
						
						}
						
			}
			else
			{
			if(email=='' && mobileno!='')
			
			{
					var pattern = /^\d{10}$/;
						if (pattern.test(mobileno)) 
						{
							var link= '<?php echo $this->getBaseUrl().'subscription/index/store'; ?>';
							jQuery.ajax({
							 type: "POST",
							 url: link,
							 data: {email:email,mobileno:mobileno},
							 success: function(msg)
							 {
							 
								 jQuery('.block-message').delay(300).fadeOut();	
								 jQuery('.success_msg').delay(1000).fadeIn();
								jQuery('.block-message').delay(8000).fadeIn(function(){jQuery('#mobileno').val('');});								
								jQuery('.success_msg').delay(7000).fadeOut();	
											  
							 }
			
						});
						return false;
							
						}
					else
					{
					//throw error
							jQuery('.mobileno-message').html('Please Enter Valid mobileno');
							jQuery('.mobileno-message').delay(8000).fadeOut();
							
							return false;
						
					}
					
		
						
			}
			else
			{
			if(email!='' && mobileno!='')
			{
				var atpos=email.indexOf("@");
						var dotpos=email.lastIndexOf(".");
						var email;
					if (atpos<1 || dotpos<atpos+2 || dotpos+2>=email.length)
					{
						jQuery('.email-message').html('Please Enter Valid Email address');
						jQuery('.email-message').delay(2000).fadeOut();
						//alert("Not a valid e-mail address");
						 email = false;
						 //alert(email);
						 return false;
					}
				
				var pattern = /^\d{10}$/;
					if (!pattern.test(mobileno)) 
					{
							jQuery('.mobileno-message').html('Please Enter Valid mobileno');
						jQuery('.mobileno-message').delay(2000).fadeOut();
						return false;
					}
				else
				{
				if(pattern.test(mobileno) && email)
				{
				//throw error
						var link= '<?php echo $this->getBaseUrl().'subscription/index/store'; ?>';
					 jQuery.ajax({
						 type: "POST",
						 url: link,
						 data: {email:email,mobileno:mobileno},
						 success: function(msg)
						 {
						 
								jQuery('.block-message').delay(300).fadeOut();	
								 jQuery('.success_msg').delay(1000).fadeIn();
								jQuery('.block-message').delay(8000).fadeIn(function(){jQuery('#mobileno').val('');jQuery('#newsletter').val('');});								
								jQuery('.success_msg').delay(7000).fadeOut();		
									
											
						 }
		
					});
					return false;
									
					
				}
				}
		
			}
					//alert('ajax requesrt');
					
		
		
		}
		
		}
		
		}
	
				
		} 
    </script>

<style type = "text/css">
.success_msg .newsletter-result-msg{

	border: 3px solid #ccc;
	padding: 5px;
	}
.success_msg{display:none;}
</style>
	