<div class="newin-container">
	
	<img src="<?php echo $this->getSkinUrl('images/new-in-top.png');?>" alt="new-in"/>
	
	<div class="new-in-text-man"><a href="<?php echo $this->getUrl('catalog/category/view/id/46')?>"><?php echo $this->__('NEW IN MAN')?></a></div>
	<div class="new-in-text-woman"><a href="<?php echo $this->getUrl('catalog/category/view/id/45')?>"><?php echo $this->__('NEW IN WOMAN')?></a></div>
	
	<img src="<?php echo $this->getSkinUrl('images/new-in-bottom.png');?>" alt="new-in"/>
	
</div> 