<ul class="products-grid last even bxslider">
                    <li class="item first">
                <a href="http://hobbistry.com/phad-painting-folk-art-of-rajasthan.html" title="Phad Painting" class="product-image"><img src="http://hobbistry.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/h/phad_front.jpg" width="200" height="160" alt="Phad Painting"></a>
                <h2 class="product-name"><a href="http://hobbistry.com/phad-painting-folk-art-of-rajasthan.html" title="Phad Painting - Folk art of Rajasthan">Phad Painting - Folk art of Rajasthan</a></h2>
                                

                
    <div class="price-box">
                                                            <span class="regular-price" id="product-price-255">
                                            <span class="price">Rs. 200.00</span>                                    </span>
                        
        </div>

                <div class="actions">
                                            <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://hobbistry.com/checkout/cart/add/uenc/aHR0cDovL2hvYmJpc3RyeS5jb20v/product/255/')"><span><span>Add to Cart</span></span></button>
                                        <ul class="add-to-links">
                                                                    </ul>
                </div>
            </li>
                                    <li class="item">
                <a href="http://hobbistry.com/diy-paint-a-pot.html" title="DIY - Paint a Pot" class="product-image"><img src="http://hobbistry.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/a/paint_a_pot_box.jpg" width="200" height="160" alt="DIY - Paint a Pot"></a>
                <h2 class="product-name"><a href="http://hobbistry.com/diy-paint-a-pot.html" title="DIY - Paint a Pot">DIY - Paint a Pot</a></h2>
                                

                
    <div class="price-box">
                                                            <span class="regular-price" id="product-price-243">
                                            <span class="price">Rs. 399.00</span>                                    </span>
                        
        </div>

                <div class="actions">
                                            <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://hobbistry.com/checkout/cart/add/uenc/aHR0cDovL2hvYmJpc3RyeS5jb20v/product/243/')"><span><span>Add to Cart</span></span></button>
                                        <ul class="add-to-links">
                                                                    </ul>
                </div>
            </li>
                                    <li class="item">
                <a href="http://hobbistry.com/purple-large-heart-leaf-shaped-appliques.html" title="Purple Large Heart- Leaf shaped Appliques" class="product-image"><img src="http://hobbistry.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/l/a/large_purple_leaf.jpg" width="200" height="160" alt="Purple Large Heart- Leaf shaped Appliques"></a>
                <h2 class="product-name"><a href="http://hobbistry.com/purple-large-heart-leaf-shaped-appliques.html" title="Purple Large Heart- Leaf shaped Appliques">Purple Large Heart- Leaf shaped Appliques</a></h2>
                                

                
    <div class="price-box">
                                                            <span class="regular-price" id="product-price-422">
                                            <span class="price">Rs. 220.00</span>                                    </span>
                        
        </div>

                <div class="actions">
                                            <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://hobbistry.com/checkout/cart/add/uenc/aHR0cDovL2hvYmJpc3RyeS5jb20v/product/422/')"><span><span>Add to Cart</span></span></button>
                                        <ul class="add-to-links">
                                                                    </ul>
                </div>
            </li>
                                    <li class="item last">
                <a href="http://hobbistry.com/warli-coaster-art.html" title="warli coaster kit" class="product-image"><img src="http://hobbistry.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/w/a/warli_coaster_kit_1.jpg" width="200" height="160" alt="warli coaster kit"></a>
                <h2 class="product-name"><a href="http://hobbistry.com/warli-coaster-art.html" title="Warli Coaster Art">Warli Coaster Art</a></h2>
                                

                
    <div class="price-box">
                                                            <span class="regular-price" id="product-price-411">
                                            <span class="price">Rs. 400.00</span>                                    </span>
                        
        </div>

                <div class="actions">
                                            <button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://hobbistry.com/checkout/cart/add/uenc/aHR0cDovL2hvYmJpc3RyeS5jb20v/product/411/')"><span><span>Add to Cart</span></span></button>
                                        <ul class="add-to-links">
                                                                    </ul>
                </div>
            </li>
                </ul>
