<?php

	/*	$resource = Mage::getSingleton('core/resource');
		$read = $resource->getConnection('core_read');*/
		$collection = Mage::getModel('content/gamechanger')->getCollection();
		/*echo '<pre>';
		print_r($collection->getData());
		exit;*/
	/*	$query = "SELECT * FROM gamechangernew order by slideno";
		$result=$read->query($query);
		$gamechanger3 = $result->fetchAll();
		//print_r($gamechanger3);
		$query2 = "SELECT * FROM gamechangernew where type='0'";
		$result2=$read->query($query2);
		$gamechanger2 = $result2->fetchAll(); */
		//print_r($gamechanger2[0]['image1']);
		
		$mediaurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		$baseurl = Mage::getBaseUrl();
		//print_r($mediaurl);
?>

	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl(); ?>images/images/styles1.css" />
	<script src="<?php echo $this->getSkinUrl(); ?>images/images/jquery.bxslider2.min.js" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
		SyntaxHighlighter.all();
	</script>
	<script>
	jQuery(function(){
	jQuery('#slides1').bxSlider({
		prev_image: '<?php echo $this->getSkinUrl();?>images/images/btn_arrow_left.png',
		next_image: '<?php echo $this->getSkinUrl();?>images/images/btn_arrow_right.png',
		wrapper_class: 'slides1_wrap',
		margin: 70,
		auto: false,
		auto_controls: true
	});
});
</script>
<style type="text/css">
#slides1 li {margin-left: 25px;}
.imageWrapper,.imageWrapper1,.imageWrapper2,.imageWrapper3 ,.imageWrapper4,.imageWrapper5  {
    position: relative;
    font-family: MS Sans Serif;font-size: 14px;text-transform: uppercase;font-weight: normal;
}
.imageWrapper img,.imageWrapper1 img,.imageWrapper2 img,.imageWrapper3 img,.imageWrapper4 img,.imageWrapper5 img {

    display: block;
}
.imageWrapper .cornerLink ,.imageWrapper1 .cornerLink,
.imageWrapper2 .cornerLink ,.imageWrapper3 .cornerLink,
.imageWrapper4 .cornerLink ,.imageWrapper5 .cornerLink{
    opacity: 0;
    position: absolute;
    bottom: 0px;
    left: 0px;
    right: 0px;
    padding: 15px 0px;
    color: #fff;
    background: #908C81;
    text-decoration: none;
    text-align: center;
    -webkit-transition: opacity 500ms;
    -moz-transition: opacity 500ms;
    -o-transition: opacity 500ms;
    transition: opacity 500ms;
    
}
.imageWrapper:hover .cornerLink ,.imageWrapper1:hover .cornerLink,
.imageWrapper2:hover .cornerLink ,.imageWrapper3:hover .cornerLink,
.imageWrapper4:hover .cornerLink ,.imageWrapper5:hover .cornerLink {
    opacity: 0.8;
}

</style>
<div class="lookArea">
	<div id="content_inner">
		<!-- end intro -->
		<!-- end sidebar_right -->
		<ul id="slides1">
			<?php foreach($collection->getData() as $gamechanger){ ?>
			<?php// echo '<pre>';
				  //print_r($gamechanger);
				  //exit;?>

			<?php if($gamechanger['type']=='0') {?>
			<li>
				<div class="singleslide">.
					<img src="<?php echo $mediaurl.''.$gamechanger['image1'] ?>" alt=""/>
				</div>
			</li>
			<?php }?>
			<?php if($gamechanger['type']=='1') {?>
		
				<li>            	
				<div class="gamechangerArea2">
					<div class="imageWrapper" style="width: 460px;height: 255px;">
						<a href="<?php echo $gamechanger['url1'] ?>" class="game_changer_img4"><img src="<?php echo $mediaurl.''.$gamechanger['image1'] ?>" /></a>
						<a href="<?php echo $gamechanger['url1'] ?>" class="cornerLink"><?php echo $gamechanger['name1']?></a>
					</div>
					<div class="imageWrapper1" style="width:223px;height:261px;float: left;">
						<a href="<?php echo $gamechanger['url2'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image2'] ?>" /></a>
						<a href="<?php echo $gamechanger['url2'] ?>" class="cornerLink"><?php echo $gamechanger['name2']?></a>
					</div>
					<div class="imageWrapper2" style="width:223px;height:261px;float:left">
						<a href="<?php echo $gamechanger['url3'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image3'] ?>" /></a>
						<a href="<?php echo $gamechanger['url3'] ?>" class="cornerLink"><?php echo $gamechanger['name3']?></a>
					</div>
				
				</div>    		
				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:223px;height:514px;float: left;">
						<a href="<?php echo $gamechanger['url4'] ?>" class="game_changer_img3"><img src="<?php echo $mediaurl.''.$gamechanger['image4'] ?>" /></a>
						<a href="<?php echo $gamechanger['url4'] ?>" class="cornerLink"><?php echo $gamechanger['name4']?></a>
					</div>
				</div>
				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:227px;height:255px;float: left;">
						<a href="<?php echo $gamechanger['url5'] ?>" class="game_changer_img1"><img src="<?php echo $mediaurl.''.$gamechanger['image5'] ?>" /></a>
						<a href="<?php echo $gamechanger['url5'] ?>" class="cornerLink"><?php echo $gamechanger['name5']?></a>
					</div>
					<div class="imageWrapper1" style="width:227px;height:255px;float: left;">
						<a href="<?php echo $gamechanger['url6'] ?>" class="game_changer_img2"><img src="<?php echo $mediaurl.''.$gamechanger['image6'] ?>" /></a>
						<a href="<?php echo $gamechanger['url6'] ?>" class="cornerLink"><?php echo $gamechanger['name6']?></a>
					</div>
				</div>
			</li>
			<?php } ?>
			<?php if($gamechanger['type']=='2') {?>
		
					
				<li>    

				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:227px;height:255px;float: left;">
						<a href="<?php echo $gamechanger['url1'] ?>" class="game_changer_img1"><img src="<?php echo $mediaurl.''.$gamechanger['image1'] ?>" /></a>
						<a href="<?php echo $gamechanger['url1'] ?>" class="cornerLink"><?php echo $gamechanger['name1']?></a>
					</div>
					<div class="imageWrapper1" style="width:227px;height:255px;float: left;">
						<a href="<?php echo $gamechanger['url2'] ?>" class="game_changer_img2"><img src="<?php echo $mediaurl.''.$gamechanger['image2'] ?>" /></a>
						<a href="<?php echo $gamechanger['url2'] ?>" class="cornerLink"><?php echo $gamechanger['name2']?></a>
					</div>
				</div>

				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:223px;height:514px;float: left;">
						<a href="<?php echo $gamechanger['url3'] ?>" class="game_changer_img3"><img src="<?php echo $mediaurl.''.$gamechanger['image3'] ?>" /></a>
						<a href="<?php echo $gamechanger['url3'] ?>" class="cornerLink"><?php echo $gamechanger['name3']?></a>
					</div>
				</div>

				<div class="gamechangerArea2">
					<div class="imageWrapper" style="width: 460px;height: 261px;">
						<a href="<?php echo $gamechanger['url4'] ?>" class="game_changer_img4"><img src="<?php echo $mediaurl.''.$gamechanger['image4'] ?>" /></a>
						<a href="<?php echo $gamechanger['url4'] ?>" class="cornerLink"><?php echo $gamechanger['name4']?></a>
					</div>
					<div class="imageWrapper1" style="width:223px;height:261px;float: left;">
						<a href="<?php echo $gamechanger['url5'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image5'] ?>" /></a>
						<a href="<?php echo $gamechanger['url5'] ?>" class="cornerLink"><?php echo $gamechanger['name5']?></a>
					</div>
					<div class="imageWrapper2" style="width:223px;height:261px;float:left">
						<a href="<?php echo $gamechanger['url6'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image6'] ?>" /></a>
						<a href="<?php echo $gamechanger['url6'] ?>" class="cornerLink"><?php echo $gamechanger['name6']?></a>
					</div>
				
				</div>                

			</li>
			<?php }?>
			<?php if($gamechanger['type']=='3') {?>
		
			<li>             
				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:223px;height:517px;float: left;">
						<a href="<?php echo $gamechanger['url1'] ?>" class="game_changer_img3"><img src="<?php echo $mediaurl.''.$gamechanger['image1'] ?>" /></a>
						<a href="<?php echo $gamechanger['url1'] ?>" class="cornerLink"><?php echo $gamechanger['name1']?></a>
					</div>
				</div>

				<div class="gamechangerArea2">
					<div class="imageWrapper" style="width: 460px;height: 248px;">
						<a href="<?php echo $gamechanger['url2'] ?>" class="game_changer_img4"><img src="<?php echo $mediaurl.''.$gamechanger['image2'] ?>" /></a>
						<a href="<?php echo $gamechanger['url2'] ?>" class="cornerLink"><?php echo $gamechanger['name2']?></a>
					</div>
					<div class="imageWrapper1" style="width:223px;height:270px;float: left;">
						<a href="<?php echo $gamechanger['url3'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image3'] ?>" /></a>
						<a href="<?php echo $gamechanger['url3'] ?>" class="cornerLink"><?php echo $gamechanger['name3']?></a>
					</div>
					<div class="imageWrapper2" style="width:237px;height:270px;float:left">
						<a href="<?php echo $gamechanger['url4'] ?>" class="game_changer_img5"><img src="<?php echo $mediaurl.''.$gamechanger['image4'] ?>" /></a>
						<a href="<?php echo $gamechanger['url4'] ?>" class="cornerLink"><?php echo $gamechanger['name4']?></a>
					</div>
				
				</div> 
				<div class="gamechangerArea1">
					<div class="imageWrapper1" style="width:227px;height:248px;float: left;">
						<a href="<?php echo $gamechanger['url5'] ?>" class="game_changer_img1"><img src="<?php echo $mediaurl.''.$gamechanger['image5'] ?>" /></a>
						<a href="<?php echo $gamechanger['url5'] ?>" class="cornerLink"><?php echo $gamechanger['name5']?></a>
					</div>
					<div class="imageWrapper1" style="width:235px;height:270px;float: left;">
						<a href="<?php echo $gamechanger['url6'] ?>" class="game_changer_img2"><img src="<?php echo $mediaurl.''.$gamechanger['image6'] ?>" /></a>
						<a href="<?php echo $gamechanger['url6'] ?>" class="cornerLink"><?php echo $gamechanger['name6']?></a>
					</div>
				</div> 
			</li>	
			<?php }?>
			<?php } ?>			
		</ul>
	</div>
</div>