<div class="block block-subscribe">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
          <h1><?php echo $this->__('BE IN THE KNOW') ?></h1>
            <p><?php echo $this->__('Be the first to know about exclusive offers, collection previews and the latest style news from French Connection via email') ?></p>
          <table>
            <tr>
              <td class="subs_label"><?php echo $this->__('Email*') ?></td>
              <td>
                <input type="text" name="email" id="newsletter email" value="<?php if(!empty($_POST['email'])){echo $_POST['email'];}?>" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('First Name*') ?></td>
              <td>
                <input type="text" name="firstname" id="newsletter name" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry" />
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('Last Name*') ?></td>
              <td>
                <input type="text" name="lastname" id="newsletter lastname" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry" />
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('Gender*') ?></td>
              <td>
                <label for="rdoGenderFemale">Female</label><input id="genderFemale" type="radio" class="gend" name="gender" value="female" <?php if(!empty($_POST['gender']) && $_POST['gender'] == 'Woman'){echo "checked='checked'";}?>>
                <label for="rdoGenderMale">Male</label><input id="genderMale" type="radio" class="gend" name="gender" value="male" <?php if(!empty($_POST['gender']) && $_POST['gender'] == 'Man'){echo "checked='checked'";}?>>
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('Country*') ?></td>
              <td>
                <!-- <input type="text" name="country" id="newsletter country" title="<?php //echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry" /> -->
                <select name="country" id="newsletter country" class="input-text required-entry selectinput" title="<?php echo $this->__('Sign up for our newsletter') ?>">
                    <option value="AL">Albania</option>
                    <option value="AU">Australia</option>
                    <option value="AT">Austria</option>
                    <option value="BY">Belarus</option>
                    <option value="BE">Belgium</option>
                    <option value="BM">Bermuda</option>
                    <option value="BR">Brazil</option>
                    <option value="BN">Brunei Darussalam</option>
                    <option value="BG">Bulgaria</option>
                    <option value="CA">Canada</option>
                    <option value="KY">Cayman Islands</option>
                    <option value="JG">Channel Islands</option>
                    <option value="CN">China</option>
                    <option value="HR">Croatia</option>
                    <option value="CY">Cyprus</option>
                    <option value="DK">Denmark</option>
                    <option value="EE">Estonia</option>
                    <option value="FI">Finland</option>
                    <option value="FR">France</option>
                    <option value="DE">Germany</option>
                    <option value="GI">Gibraltar</option>
                    <option value="GR">Greece</option>
                    <option value="HK">Hong Kong</option>
                    <option value="HU">Hungary</option>
                    <option value="IS">Iceland</option>
                    <option selected="selected" value="IN">India</option>
                    <option value="IE">Ireland</option>
                    <option value="IL">Israel</option>
                    <option value="IT">Italy</option>
                    <option value="JP">Japan</option>
                    <option value="KZ">Kazakhstan</option>
                    <option value="KP">Korea, Democratic People's Republic Of</option>
                    <option value="KR">Korea, Republic Of</option>
                    <option value="KW">Kuwait</option>
                    <option value="LV">Latvia</option>
                    <option value="LT">Lithuania</option>
                    <option value="LU">Luxembourg</option>
                    <option value="MK">Macedonia, The Former Yugoslav Republic Of</option>
                    <option value="MY">Malaysia</option>
                    <option value="MT">Malta</option>
                    <option value="MU">Mauritius</option>
                    <option value="MX">Mexico</option>
                    <option value="MD">Moldova, Republic Of</option>
                    <option value="ME">Montenegro</option>
                    <option value="NL">Netherlands</option>
                    <option value="NZ">New Zealand</option>
                    <option value="NG">Nigeria</option>
                    <option value="NO">Norway</option>
                    <option value="PK">Pakistan</option>
                    <option value="PL">Poland</option>
                    <option value="PT">Portugal</option>
                    <option value="RO">Romania</option>
                    <option value="RU">Russian Federation</option>
                    <option value="SA">Saudi Arabia</option>
                    <option value="RS">Serbia, Republic Of</option>
                    <option value="SG">Singapore</option>
                    <option value="SK">Slovakia</option>
                    <option value="SI">Slovenia</option>
                    <option value="ZA">South Africa</option>
                    <option value="ES">Spain</option>
                    <option value="SE">Sweden</option>
                    <option value="CH">Switzerland</option>
                    <option value="TW">Taiwan, Province Of China</option>
                    <option value="TR">Turkey</option>
                    <option value="UA">Ukraine</option>
                    <option value="AE">United Arab Emirates</option>
                    <option value="GB">United Kingdom</option>
                    <option value="US">United States</option>

                  </select>
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('Postcode*') ?></td>
              <td>
                <input type="text" name="postcode" id="newsletter postcode" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry"/>
              </td>
            </tr>
            <tr>
              <td class="subs_label"><?php echo $this->__('Mobile Number') ?></td>
              <td>
                <input type="text" name="mobileno" id="newsletter mobileno" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text" />
              </td>
            </tr>
            <tr>
              <td colspan="2" class="form_note"><?php echo $this->__('Get invited to exclusive events and receive texts about flash sales.') ?></td>
            </tr>
            <tr>
              <td>
                <div class="actions">
                  <button type="submit" title="<?php echo $this->__('submit') ?>" class="button subscrb-button"><span><span><?php echo $this->__('submit') ?></span></span></button>
                </div>
              </td>
              <td></td>
            </tr>
          </table>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>
