<style>
	strong
	{
		color:#222;
	}
.categoryname[href="<?php echo $this->getBaseUrl(); ?>woman/category.html"],
.categoryname[href="<?php echo $this->getBaseUrl(); ?>woman/category-5.html"],
.categoryname[href="<?php echo $this->getBaseUrl(); ?>man/category.html"],
.categoryname[href="<?php echo $this->getBaseUrl(); ?>man/category-12.html"],
.categoryname[href="<?php echo $this->getBaseUrl(); ?>underwear/category.html"]

{
	display:none
}
</style>

<?php
    $_rtl           = Mage::getStoreConfig('custom_menu/general/rtl') + 0;
    $_categories    = $this->getStoreCategories();
    if (is_object($_categories)) $_categories = $this->getStoreCategories()->getNodes();
?>
<div class="nav-container">
    <div id="custommenu" class="<?php echo $_rtl ? ' rtl' : ''; ?>">
        <?php if ($this->showHomeLink()) : ?>
        <div class="menu">
            <div class="parentMenu menu0">
                <a href="<?php echo $this->getUrl('') ?>">
                    <span><?php echo $this->__('Home'); ?></span>
                </a>
            </div>
        </div>
        <?php endif ?>
		
        <?php foreach ($_categories as $_category): ?>
            <?php echo $this->drawCustomMenuItem($_category) ?>
        <?php endforeach ?>
				


<div class="menu">
    <div class="parentMenu">
        <a href="http://911fashion.frenchconnection.in">
            <span  id="inspire"><?php echo $this->__('Blog'); ?></span>
        </a>
    </div>
</div>

        <div class="clearBoth"></div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = <?php echo Mage::getStoreConfig('custom_menu/popup/width') + 0; ?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo Mage::getStoreConfig('custom_menu/popup/top_offset') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_DISPLAYING = <?php echo Mage::getStoreConfig('custom_menu/popup/delay_displaying') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_HIDING = <?php echo Mage::getStoreConfig('custom_menu/popup/delay_hiding') + 0; ?>;
var CUSTOMMENU_RTL_MODE = <?php echo $_rtl; ?>;
var wpCustommenuTimerShow = {};
var wpCustommenuTimerHide = {};
var wpActiveMenu = null;
//]]>
</script>



