<style type="text/css">
.catalog-category-view #section0 { background: #CAD2D5; }
#section1 { background: #f1f1f1; }

.man_banner_five { background:url('<?php echo $this->getSkinUrl(); ?>images/zaid/banner_man.jpg') no-repeat center top;  background-size: auto 100%; width: 100%; height: 100%; }
.man_banner_six { background:url('<?php echo $this->getSkinUrl(); ?>images/zaid/banner_man1.jpg') no-repeat center top;  background-size: auto 100%; width: 100%; height: 100%; }
</style>




<div class="section" id="section0">
	<div class="down" id="section1link"><a  href="#"></a></div>
	<div class="banner_container man_banner_five">&nbsp;</div>
	<?php $model= Mage::getModel("catalog/category") ?>	
	
    <div class="banner_message">
        <div class="banner_message_title">man<br>Spring<br>2014</div>
        <!-- <div class="banner_message_text"></div> -->
        <a href="<?php echo $this->getBaseUrl.'man/category3/man-shirts.html';?>" class="banner_cta" >shop new in</a>
    </div>
	
</div>
<div class="section" id="section1">
	<div class="up" id="section0link"><a  href="#"></a></div>
	<!-- <div class="down" id="section2link"><a  href="#"></a></div> -->
	<?php  $url= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);  ?>
	<div class="banner_container man_banner_six">&nbsp;</div>
	

    <div class="banner_message">
        <div class="banner_message_title">The Essentials</div>
        <div class="banner_message_text">Building the base layers to your every <br>day wardrobe has never been easier.</div>
        <a href="/content/features/essentials_man.htm" class="banner_cta"> view the feature</a>
    </div>

</div>