<style type="text/css">
.banner_one { background:url("<?php echo $this->getSkinUrl(); ?>images/zaid/banner.jpg") no-repeat center top;  background-size: auto 100%;  }
.banner_two { background:url("<?php echo $this->getSkinUrl(); ?>images/zaid/banner_campaign_video.jpg") no-repeat center top;  background-size: auto 100%;  }
</style>
<div class="section" id="section0">
	<div class="down" id="section1link"><a  href="#"></a></div>
	<div class="banner_container banner_one">&nbsp;</div>
	
</div>
<div class="section" id="section1">
	<div class="up" id="section0link"><a  href="#"></a></div>
	<?php  $url= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);  ?>
	<a href="<?php echo $url."fcuk_feb.mp4"?>" class="fancybox iframe">
		<div class="banner_container banner_two">&nbsp;</div>
	</a>	
	<div class="banner_message banner_message_white">
        <div class="banner_message_title">Models<br>In Motion</div>
        <div class="banner_message_text">See what mischief the models got up <br>to on our campaign shoot </div>
        <a href="<?php echo $url."fcuk_feb.mp4"?>" class="fancybox iframe" id="banner_cta_02">watch now</a>        
    </div>
</div>
<!-- <div class="section" id="section2">
	<div class="up" id="section1link"><a  href="#"></a></div>
	<a href="<?php //echo $url."fcuk_feb.mp4"?>" class="fancybox iframe" id="modelinmotion">
		<div class="banner_container banner_two">&nbsp;</div>
	</a>	
	<div class="banner_message banner_message_white">
        <div class="banner_message_title">Models<br>In Motion</div>
        <div class="banner_message_text">See what mischief the models got up <br>to on our campaign shoot </div>
        <a href="<?php //echo $url."fcuk.mp4"?>" class="fancybox iframe" id="banner_cta_02">watch now</a>        
    </div>
</div> -->


